run:
  concurrency: 12
  deadline: 5m
  issues-exit-code: 1
  tests: true
  # skip-dirs:
  skip-files:
    - ".*\\.pb\\.go"
    - ".*(.|_)gen\\.go"
  modules-download-mode: readonly

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/davecgh/go-spew/spew
  errcheck:
    check-type-assertions: true
    check-blank: true
    # exclude: .errcheckignore
  goconst:
    min-len: 3
    min-occurrences: 3
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/go-language-server/protocol/
  golint:
    min-confidence: 0.3
  govet:
    check-shadowing: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32
  # maligned:
  #   suggest-new: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true  # Report preallocation suggestions on range loops, true by default
    for-loops: false  # Report preallocation suggestions on for loops, false by default
  unparam:
    algo: cha
    check-exported: true
  unused:
    check-exported: true

linters:
  enable:
  enable-all: true
  disable:
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gosec
    - lll
    - maligned
    - megacheck
    - typecheck
  fast: true

issues:
  exclude-use-default: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
