run:
  concurrency: 12
  deadline: 5m
  issues-exit-code: 1
  tests: true
  # skip-dirs:
  skip-files:
    - ".*\\.pb\\.go"
  modules-download-mode: vendor

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude: .errcheckignore
  goconst:
    min-len: 3
    min-occurrences: 3
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/go-language-server/protocol/
  golint:
    min-confidence: 0.3
  govet:
    check-shadowing: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  unparam:
    algo: cha
    check-exported: true
  unused:
    check-exported: true

linters:
  enable:
  enable-all: true
  disable:
    # - dupl
    # - gochecknoglobals
    # - gochecknoinits
    # - gocyclo
    # - gosec
    - lll
    # - maligned
    # - megacheck
    # - typecheck
  fast: true

issues:
  exclude-use-default: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
