// Copyright 2026 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by internal/genlsp from metaModel.json; DO NOT EDIT.

package protocol

// CallHierarchyPrepareParams The parameter of a `textDocument/prepareCallHierarchy` request.
//
// @since 3.16.0
//
// Since: 3.16.0
type CallHierarchyPrepareParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
}

// CallHierarchyItem Represents programming constructs like functions or constructors in the context
// of call hierarchy.
//
// @since 3.16.0
//
// Since: 3.16.0
type CallHierarchyItem struct {
	// Name The name of this item.
	Name string `json:"name"`

	// Kind The kind of this item.
	Kind SymbolKind `json:"kind"`

	// Tags Tags for this item.
	Tags []SymbolTag `json:"tags,omitzero"`

	// Detail More detail for this item, e.g. the signature of a function.
	Detail *string `json:"detail,omitzero"`

	// URI The resource identifier of this item.
	URI DocumentURI `json:"uri"`

	// Range The range enclosing this symbol not including leading/trailing whitespace but everything else, e.g. comments and code.
	Range Range `json:"range"`

	// SelectionRange The range that should be selected and revealed when this symbol is being picked, e.g. the name of a function.
	// Must be contained by the {@link CallHierarchyItem.range `range`}.
	SelectionRange Range `json:"selectionRange"`

	// Data A data entry field that is preserved between a call hierarchy prepare and
	// incoming calls or outgoing calls requests.
	Data LSPAny `json:"data,omitzero"`
}

// CallHierarchyRegistrationOptions Call hierarchy options used during static or dynamic registration.
//
// @since 3.16.0
//
// Since: 3.16.0
type CallHierarchyRegistrationOptions struct {
	TextDocumentRegistrationOptions
	CallHierarchyOptions
	StaticRegistrationOptions
}

// CallHierarchyIncomingCallsParams The parameter of a `callHierarchy/incomingCalls` request.
//
// @since 3.16.0
//
// Since: 3.16.0
type CallHierarchyIncomingCallsParams struct {
	WorkDoneProgressParams
	PartialResultParams

	// Item is defined by the LSP specification.
	Item CallHierarchyItem `json:"item"`
}

// CallHierarchyIncomingCall Represents an incoming call, e.g. a caller of a method or constructor.
//
// @since 3.16.0
//
// Since: 3.16.0
type CallHierarchyIncomingCall struct {
	// From The item that makes the call.
	From CallHierarchyItem `json:"from"`

	// FromRanges The ranges at which the calls appear. This is relative to the caller
	// denoted by {@link CallHierarchyIncomingCall.from `this.from`}.
	FromRanges []Range `json:"fromRanges"`
}

// CallHierarchyOutgoingCallsParams The parameter of a `callHierarchy/outgoingCalls` request.
//
// @since 3.16.0
//
// Since: 3.16.0
type CallHierarchyOutgoingCallsParams struct {
	WorkDoneProgressParams
	PartialResultParams

	// Item is defined by the LSP specification.
	Item CallHierarchyItem `json:"item"`
}

// CallHierarchyOutgoingCall Represents an outgoing call, e.g. calling a getter from a method or a method from a constructor etc.
//
// @since 3.16.0
//
// Since: 3.16.0
type CallHierarchyOutgoingCall struct {
	// To The item that is called.
	To CallHierarchyItem `json:"to"`

	// FromRanges The range at which this item is called. This is the range relative to the caller, e.g the item
	// passed to {@link CallHierarchyItemProvider.provideCallHierarchyOutgoingCalls `provideCallHierarchyOutgoingCalls`}
	// and not {@link CallHierarchyOutgoingCall.to `this.to`}.
	FromRanges []Range `json:"fromRanges"`
}

// CallHierarchyOptions Call hierarchy options used during static registration.
//
// @since 3.16.0
//
// Since: 3.16.0
type CallHierarchyOptions struct {
	WorkDoneProgressOptions
}

// CallHierarchyClientCapabilities @since 3.16.0
//
// Since: 3.16.0
type CallHierarchyClientCapabilities struct {
	// DynamicRegistration Whether implementation supports dynamic registration. If this is set to `true`
	// the client supports the new `(TextDocumentRegistrationOptions & StaticRegistrationOptions)`
	// return value for the corresponding server capability as well.
	DynamicRegistration *bool `json:"dynamicRegistration,omitzero"`
}
