// Copyright 2026 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by internal/genlsp from metaModel.json; DO NOT EDIT.

package protocol

// CodeLensParams The parameters of a {@link CodeLensRequest}.
type CodeLensParams struct {
	WorkDoneProgressParams
	PartialResultParams

	// TextDocument The document to request code lens for.
	TextDocument TextDocumentIdentifier `json:"textDocument"`
}

// CodeLens A code lens represents a {@link Command command} that should be shown along with
// source text, like the number of references, a way to run tests, etc.
//
// A code lens is _unresolved_ when no command is associated to it. For performance
// reasons the creation of a code lens and resolving should be done in two stages.
type CodeLens struct {
	// Range The range in which this code lens is valid. Should only span a single line.
	Range Range `json:"range"`

	// Command The command this code lens represents.
	Command Command `json:"command,omitzero"`

	// Data A data entry field that is preserved on a code lens item between
	// a {@link CodeLensRequest} and a {@link CodeLensResolveRequest}
	Data LSPAny `json:"data,omitzero"`
}

// CodeLensRegistrationOptions Registration options for a {@link CodeLensRequest}.
type CodeLensRegistrationOptions struct {
	TextDocumentRegistrationOptions
	CodeLensOptions
}

// CodeLensOptions Code Lens provider options of a {@link CodeLensRequest}.
type CodeLensOptions struct {
	WorkDoneProgressOptions

	// ResolveProvider Code lens has a resolve provider as well.
	ResolveProvider *bool `json:"resolveProvider,omitzero"`
}

// CodeLensWorkspaceClientCapabilities @since 3.16.0
//
// Since: 3.16.0
type CodeLensWorkspaceClientCapabilities struct {
	// RefreshSupport Whether the client implementation supports a refresh request sent from the
	// server to the client.
	//
	// Note that this event is global and will force the client to refresh all
	// code lenses currently shown. It should be used with absolute care and is
	// useful for situation where a server for example detect a project wide
	// change that requires such a calculation.
	RefreshSupport *bool `json:"refreshSupport,omitzero"`
}

// CodeLensClientCapabilities The client capabilities  of a {@link CodeLensRequest}.
type CodeLensClientCapabilities struct {
	// DynamicRegistration Whether code lens supports dynamic registration.
	DynamicRegistration *bool `json:"dynamicRegistration,omitzero"`

	// ResolveSupport Whether the client supports resolving additional code lens
	// properties via a separate `codeLens/resolve` request.
	//
	// @since 3.18.0
	//
	// Since: 3.18.0
	ResolveSupport ClientCodeLensResolveOptions `json:"resolveSupport,omitzero"`
}

// ClientCodeLensResolveOptions @since 3.18.0
//
// Since: 3.18.0
type ClientCodeLensResolveOptions struct {
	// Properties The properties that a client can resolve lazily.
	Properties []string `json:"properties"`
}
