// Copyright 2026 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by internal/genlsp from metaModel.json; DO NOT EDIT.

package protocol

import (
	"errors"
	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
)

func (x *CompletionItem) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	switch dec.PeekKind() {
	case 'n':
		*x = CompletionItem{}
		_, err := dec.ReadToken()
		return err
	case '{':
	default:
		return errors.ErrUnsupported
	}
	if _, err := dec.ReadToken(); err != nil {
		return err
	}
	for dec.PeekKind() != '}' {
		key, err := dec.ReadToken()
		if err != nil {
			return err
		}
		switch key.String() {
		case "label":
			if err := decodeStringLikeFrom(dec, &x.Label); err != nil {
				return err
			}
		case "labelDetails":
			if err := json.UnmarshalDecode(dec, &x.LabelDetails, json.WithUnmarshalers(unionUnmarshalers)); err != nil {
				return err
			}
		case "kind":
			if err := decodeUint32From(dec, &x.Kind); err != nil {
				return err
			}
		case "tags":
			if err := json.UnmarshalDecode(dec, &x.Tags, json.WithUnmarshalers(unionUnmarshalers)); err != nil {
				return err
			}
		case "detail":
			if err := decodeOptionalStringFrom(dec, &x.Detail); err != nil {
				return err
			}
		case "documentation":
			if err := decodeInlayHintTooltipFrom(dec, &x.Documentation); err != nil {
				return err
			}
		case "deprecated":
			if err := decodeOptionalBoolFrom(dec, &x.Deprecated); err != nil {
				return err
			}
		case "preselect":
			if err := decodeOptionalBoolFrom(dec, &x.Preselect); err != nil {
				return err
			}
		case "sortText":
			if err := decodeOptionalStringFrom(dec, &x.SortText); err != nil {
				return err
			}
		case "filterText":
			if err := decodeOptionalStringFrom(dec, &x.FilterText); err != nil {
				return err
			}
		case "insertText":
			if err := decodeOptionalStringFrom(dec, &x.InsertText); err != nil {
				return err
			}
		case "insertTextFormat":
			if err := decodeUint32From(dec, &x.InsertTextFormat); err != nil {
				return err
			}
		case "insertTextMode":
			if err := decodeUint32From(dec, &x.InsertTextMode); err != nil {
				return err
			}
		case "textEdit":
			if err := json.UnmarshalDecode(dec, &x.TextEdit, json.WithUnmarshalers(unionUnmarshalers)); err != nil {
				return err
			}
		case "textEditText":
			if err := decodeOptionalStringFrom(dec, &x.TextEditText); err != nil {
				return err
			}
		case "additionalTextEdits":
			if err := json.UnmarshalDecode(dec, &x.AdditionalTextEdits, json.WithUnmarshalers(unionUnmarshalers)); err != nil {
				return err
			}
		case "commitCharacters":
			if err := json.UnmarshalDecode(dec, &x.CommitCharacters, json.WithUnmarshalers(unionUnmarshalers)); err != nil {
				return err
			}
		case "command":
			if err := json.UnmarshalDecode(dec, &x.Command, json.WithUnmarshalers(unionUnmarshalers)); err != nil {
				return err
			}
		case "data":
			if err := json.UnmarshalDecode(dec, &x.Data, json.WithUnmarshalers(unionUnmarshalers)); err != nil {
				return err
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	_, err := dec.ReadToken()
	return err
}

func (x *Diagnostic) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	switch dec.PeekKind() {
	case 'n':
		*x = Diagnostic{}
		_, err := dec.ReadToken()
		return err
	case '{':
	default:
		return errors.ErrUnsupported
	}
	if _, err := dec.ReadToken(); err != nil {
		return err
	}
	for dec.PeekKind() != '}' {
		key, err := dec.ReadToken()
		if err != nil {
			return err
		}
		switch key.String() {
		case "range":
			if err := decodeRangeFrom(dec, &x.Range); err != nil {
				return err
			}
		case "severity":
			if err := decodeUint32From(dec, &x.Severity); err != nil {
				return err
			}
		case "code":
			if err := decodeProgressTokenFrom(dec, &x.Code); err != nil {
				return err
			}
		case "codeDescription":
			if err := json.UnmarshalDecode(dec, &x.CodeDescription, json.WithUnmarshalers(unionUnmarshalers)); err != nil {
				return err
			}
		case "source":
			if err := decodeOptionalStringFrom(dec, &x.Source); err != nil {
				return err
			}
		case "message":
			if err := decodeInlayHintTooltipFrom(dec, &x.Message); err != nil {
				return err
			}
		case "tags":
			if err := decodeDiagnosticTagsFrom(dec, &x.Tags); err != nil {
				return err
			}
		case "relatedInformation":
			if err := json.UnmarshalDecode(dec, &x.RelatedInformation, json.WithUnmarshalers(unionUnmarshalers)); err != nil {
				return err
			}
		case "data":
			if err := json.UnmarshalDecode(dec, &x.Data, json.WithUnmarshalers(unionUnmarshalers)); err != nil {
				return err
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	_, err := dec.ReadToken()
	return err
}

func (x *PublishDiagnosticsParams) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	switch dec.PeekKind() {
	case 'n':
		*x = PublishDiagnosticsParams{}
		_, err := dec.ReadToken()
		return err
	case '{':
	default:
		return errors.ErrUnsupported
	}
	if _, err := dec.ReadToken(); err != nil {
		return err
	}
	for dec.PeekKind() != '}' {
		key, err := dec.ReadToken()
		if err != nil {
			return err
		}
		switch key.String() {
		case "uri":
			if err := decodeStringLikeFrom(dec, &x.URI); err != nil {
				return err
			}
		case "version":
			if err := decodeOptionalInt32From(dec, &x.Version); err != nil {
				return err
			}
		case "diagnostics":
			if err := json.UnmarshalDecode(dec, &x.Diagnostics, json.WithUnmarshalers(unionUnmarshalers)); err != nil {
				return err
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	_, err := dec.ReadToken()
	return err
}
