// Copyright 2026 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by internal/genlsp from metaModel.json; DO NOT EDIT.

package protocol

// DefinitionLink Information about where a symbol is defined.
//
// Provides additional metadata over normal {@link Location location} definitions, including the range of
// the defining symbol
type DefinitionLink LocationLink

// DefinitionParams Parameters for a {@link DefinitionRequest}.
type DefinitionParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	PartialResultParams
}

// DefinitionRegistrationOptions Registration options for a {@link DefinitionRequest}.
type DefinitionRegistrationOptions struct {
	TextDocumentRegistrationOptions
	DefinitionOptions
}

// DefinitionOptions Server Capabilities for a {@link DefinitionRequest}.
type DefinitionOptions struct {
	WorkDoneProgressOptions
}

// DefinitionClientCapabilities Client Capabilities for a {@link DefinitionRequest}.
type DefinitionClientCapabilities struct {
	// DynamicRegistration Whether definition supports dynamic registration.
	DynamicRegistration *bool `json:"dynamicRegistration,omitzero"`

	// LinkSupport The client supports additional metadata in the form of definition links.
	//
	// @since 3.14.0
	//
	// Since: 3.14.0
	LinkSupport *bool `json:"linkSupport,omitzero"`
}
