// Copyright 2026 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by internal/genlsp from metaModel.json; DO NOT EDIT.

package protocol

import (
	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
)

func (x CompletionItem) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String("label")); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String(x.Label)); err != nil {
		return err
	}
	if x.LabelDetails != nil {
		if err := enc.WriteToken(jsontext.String("labelDetails")); err != nil {
			return err
		}
		if err := json.MarshalEncode(enc, x.LabelDetails); err != nil {
			return err
		}
	}
	if x.Kind != 0 {
		if err := enc.WriteToken(jsontext.String("kind")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.Uint(uint64(x.Kind))); err != nil {
			return err
		}
	}
	if len(x.Tags) > 0 {
		if err := enc.WriteToken(jsontext.String("tags")); err != nil {
			return err
		}
		if err := json.MarshalEncode(enc, x.Tags); err != nil {
			return err
		}
	}
	if v, ok := x.Detail.Get(); ok {
		if err := enc.WriteToken(jsontext.String("detail")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.String(v)); err != nil {
			return err
		}
	}
	if x.Documentation != nil {
		if err := enc.WriteToken(jsontext.String("documentation")); err != nil {
			return err
		}
		if v, ok := x.Documentation.(String); ok {
			if err := enc.WriteToken(jsontext.String(string(v))); err != nil {
				return err
			}
		} else if err := json.MarshalEncode(enc, x.Documentation); err != nil {
			return err
		}
	}
	if v, ok := x.Deprecated.Get(); ok {
		if err := enc.WriteToken(jsontext.String("deprecated")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.Bool(v)); err != nil {
			return err
		}
	}
	if v, ok := x.Preselect.Get(); ok {
		if err := enc.WriteToken(jsontext.String("preselect")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.Bool(v)); err != nil {
			return err
		}
	}
	if v, ok := x.SortText.Get(); ok {
		if err := enc.WriteToken(jsontext.String("sortText")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.String(v)); err != nil {
			return err
		}
	}
	if v, ok := x.FilterText.Get(); ok {
		if err := enc.WriteToken(jsontext.String("filterText")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.String(v)); err != nil {
			return err
		}
	}
	if v, ok := x.InsertText.Get(); ok {
		if err := enc.WriteToken(jsontext.String("insertText")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.String(v)); err != nil {
			return err
		}
	}
	if x.InsertTextFormat != 0 {
		if err := enc.WriteToken(jsontext.String("insertTextFormat")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.Uint(uint64(x.InsertTextFormat))); err != nil {
			return err
		}
	}
	if x.InsertTextMode != 0 {
		if err := enc.WriteToken(jsontext.String("insertTextMode")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.Uint(uint64(x.InsertTextMode))); err != nil {
			return err
		}
	}
	if x.TextEdit != nil {
		if err := enc.WriteToken(jsontext.String("textEdit")); err != nil {
			return err
		}
		if err := json.MarshalEncode(enc, x.TextEdit); err != nil {
			return err
		}
	}
	if v, ok := x.TextEditText.Get(); ok {
		if err := enc.WriteToken(jsontext.String("textEditText")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.String(v)); err != nil {
			return err
		}
	}
	if len(x.AdditionalTextEdits) > 0 {
		if err := enc.WriteToken(jsontext.String("additionalTextEdits")); err != nil {
			return err
		}
		if err := json.MarshalEncode(enc, x.AdditionalTextEdits); err != nil {
			return err
		}
	}
	if len(x.CommitCharacters) > 0 {
		if err := enc.WriteToken(jsontext.String("commitCharacters")); err != nil {
			return err
		}
		if err := json.MarshalEncode(enc, x.CommitCharacters); err != nil {
			return err
		}
	}
	if !isZeroCommand(x.Command) {
		if err := enc.WriteToken(jsontext.String("command")); err != nil {
			return err
		}
		if err := json.MarshalEncode(enc, x.Command); err != nil {
			return err
		}
	}
	if len(x.Data) > 0 {
		if err := enc.WriteToken(jsontext.String("data")); err != nil {
			return err
		}
		if err := enc.WriteValue(x.Data); err != nil {
			return err
		}
	}
	return enc.WriteToken(jsontext.EndObject)
}

func (x Diagnostic) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String("range")); err != nil {
		return err
	}
	if err := encodeRangeTo(enc, x.Range); err != nil {
		return err
	}
	if x.Severity != 0 {
		if err := enc.WriteToken(jsontext.String("severity")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.Uint(uint64(x.Severity))); err != nil {
			return err
		}
	}
	if x.Code != nil {
		if err := enc.WriteToken(jsontext.String("code")); err != nil {
			return err
		}
		if err := encodeProgressTokenTo(enc, x.Code); err != nil {
			return err
		}
	}
	if x.CodeDescription != (CodeDescription{}) {
		if err := enc.WriteToken(jsontext.String("codeDescription")); err != nil {
			return err
		}
		if err := json.MarshalEncode(enc, x.CodeDescription); err != nil {
			return err
		}
	}
	if v, ok := x.Source.Get(); ok {
		if err := enc.WriteToken(jsontext.String("source")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.String(v)); err != nil {
			return err
		}
	}
	if err := enc.WriteToken(jsontext.String("message")); err != nil {
		return err
	}
	if v, ok := x.Message.(String); ok {
		if err := enc.WriteToken(jsontext.String(string(v))); err != nil {
			return err
		}
	} else if err := json.MarshalEncode(enc, x.Message); err != nil {
		return err
	}
	if !x.Tags.IsZero() {
		if err := enc.WriteToken(jsontext.String("tags")); err != nil {
			return err
		}
		if err := encodeDiagnosticTagsTo(enc, x.Tags); err != nil {
			return err
		}
	}
	if len(x.RelatedInformation) > 0 {
		if err := enc.WriteToken(jsontext.String("relatedInformation")); err != nil {
			return err
		}
		if err := json.MarshalEncode(enc, x.RelatedInformation); err != nil {
			return err
		}
	}
	if len(x.Data) > 0 {
		if err := enc.WriteToken(jsontext.String("data")); err != nil {
			return err
		}
		if err := enc.WriteValue(x.Data); err != nil {
			return err
		}
	}
	return enc.WriteToken(jsontext.EndObject)
}

func (x PublishDiagnosticsParams) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String("uri")); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String(string(x.URI))); err != nil {
		return err
	}
	if v, ok := x.Version.Get(); ok {
		if err := enc.WriteToken(jsontext.String("version")); err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.Int(int64(v))); err != nil {
			return err
		}
	}
	if err := enc.WriteToken(jsontext.String("diagnostics")); err != nil {
		return err
	}
	if err := json.MarshalEncode(enc, x.Diagnostics); err != nil {
		return err
	}
	return enc.WriteToken(jsontext.EndObject)
}

func (x WorkspaceSymbolSlice) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginArray); err != nil {
		return err
	}
	for _, v := range x {
		if err := encodeWorkspaceSymbolTo(enc, v); err != nil {
			return err
		}
	}
	return enc.WriteToken(jsontext.EndArray)
}
