// Copyright 2024 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by internal/genlsp from metaModel.json; DO NOT EDIT.

package protocol

// ImplementationParams is defined by the LSP specification.
type ImplementationParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	PartialResultParams
}

// ImplementationRegistrationOptions is defined by the LSP specification.
type ImplementationRegistrationOptions struct {
	TextDocumentRegistrationOptions
	ImplementationOptions
	StaticRegistrationOptions
}

// ImplementationOptions is defined by the LSP specification.
type ImplementationOptions struct {
	WorkDoneProgressOptions
}

// ImplementationClientCapabilities @since 3.6.0
//
// Since: 3.6.0
type ImplementationClientCapabilities struct {
	// DynamicRegistration Whether implementation supports dynamic registration. If this is set to `true`
	// the client supports the new `ImplementationRegistrationOptions` return value
	// for the corresponding server capability as well.
	DynamicRegistration *bool `json:"dynamicRegistration,omitzero"`

	// LinkSupport The client supports additional metadata in the form of definition links.
	//
	// @since 3.14.0
	//
	// Since: 3.14.0
	LinkSupport *bool `json:"linkSupport,omitzero"`
}
