// Copyright 2024 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

package protocol

import (
	"reflect"
	"slices"
	"sync"

	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
)

// wireOptions relaxes jsontext validation that the LSP wire contract does not
// require. Duplicate member names decode as last-wins instead of erroring
// (peers are trusted; the union dispatch scanner is presence-based and agrees),
// and strings carrying invalid UTF-8 are mangled to U+FFFD instead of
// rejecting the whole message. Both checks otherwise run per token on every
// hot encode/decode path (the duplicate tracking alone maintains a per-object
// name namespace).
var wireOptions = json.JoinOptions(
	jsontext.AllowDuplicateNames(true),
	jsontext.AllowInvalidUTF8(true),
)

// unmarshalOptions returns the canonical decode option set: relaxed wire
// validation plus the generated union dispatchers. It is built lazily because
// unionUnmarshalers is assigned in a generated init function (a package-level
// var initializer referencing it would either capture nil — var initializers
// run before init — or, if the generator emitted a var initializer instead,
// form the initialization cycle unionUnmarshalers → unmarshalX → decodeWith →
// unmarshalOptions → unionUnmarshalers).
var unmarshalOptions = sync.OnceValue(func() json.Options {
	return json.JoinOptions(wireOptions, json.WithUnmarshalers(unionUnmarshalers))
})

// Marshal encodes v as LSP-conformant JSON.
//
// Sealed-interface union values marshal as their dynamic concrete arm, so no
// custom marshalers are required. Root semantic-token payloads use a direct
// append path for their uint32 data array because they dominate encode cost in
// the benchmark corpus.
func Marshal(v any) ([]byte, error) {
	switch x := v.(type) {
	case SemanticTokens:
		return appendSemanticTokensJSON(nil, x.ResultID, x.Data), nil
	case *SemanticTokens:
		if x == nil {
			return []byte("null"), nil
		}
		return appendSemanticTokensJSON(nil, x.ResultID, x.Data), nil
	case SemanticTokensPartialResult:
		return appendSemanticTokensDataObject(nil, x.Data), nil
	case *SemanticTokensPartialResult:
		if x == nil {
			return []byte("null"), nil
		}
		return appendSemanticTokensDataObject(nil, x.Data), nil
	case *CompletionResult:
		if x == nil {
			return []byte("null"), nil
		}
		return appendCompletionResultJSON(nil, *x)
	case *WorkspaceSymbolResult:
		if x == nil {
			return []byte("null"), nil
		}
		return appendWorkspaceSymbolResultJSON(nil, *x)
	case *SymbolInformation:
		return appendSymbolInformationJSON(nil, x), nil
	}
	if m, ok := v.(appendMarshaler); ok {
		return m.appendLSPJSON(nil)
	}
	return json.Marshal(v, wireOptions)
}

// byteUnmarshaler is implemented by every generated type carrying a
// byte-level decode walker; Unmarshal routes such destinations straight into
// the walker without constructing a decoder.
type byteUnmarshaler interface {
	unmarshalLSPValue(raw jsontext.Value) error
}

// Unmarshal decodes LSP JSON into v, dispatching every generated union type to
// its discriminating decoder. Duplicate object keys decode as last-wins and
// invalid UTF-8 is replaced with U+FFFD (see wireOptions). Destinations
// covered by the generated byte walkers decode without reflection.
//
// Byte-walker destinations make one GC-managed copy of data before decoding.
// Unescaped strings and raw JSON value fields may alias that owned per-message
// copy, so callers may mutate or reuse data after Unmarshal returns. Retaining
// such fields can keep the whole owned message copy live; use Clone to detach a
// protocol value when it must outlive a much larger input message.
func Unmarshal(data []byte, v any) error {
	if isNilUnmarshalDestination(v) {
		return json.Unmarshal(data, v, unmarshalOptions())
	}
	var owned []byte
	own := func() []byte {
		if owned == nil {
			owned = slices.Clone(data)
		}
		return owned
	}
	if u, ok := v.(byteUnmarshaler); ok {
		return u.unmarshalLSPValue(own())
	}
	if ok, err := unmarshalUnionRoot(data, v); ok {
		return err
	}
	return json.Unmarshal(data, v, unmarshalOptions())
}

func isNilUnmarshalDestination(v any) bool {
	if v == nil {
		return true
	}
	rv := reflect.ValueOf(v)
	return rv.Kind() == reflect.Pointer && rv.IsNil()
}

// decodeWith decodes raw into v with the union unmarshalers applied, so that
// generated union decoders propagate dispatch to nested union fields. The
// generated decoders call this instead of json.Unmarshal directly.
func decodeWith(raw []byte, v any) error {
	return json.Unmarshal(raw, v, unmarshalOptions())
}
