// Copyright 2026 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by internal/genlsp from metaModel.json; DO NOT EDIT.

package protocol

// PublishDiagnosticsParams The publish diagnostic notification's parameters.
type PublishDiagnosticsParams struct {
	// URI The URI for which diagnostic information is reported.
	URI DocumentURI `json:"uri"`

	// Version Optional the version number of the document the diagnostics are published for.
	//
	// @since 3.15.0
	//
	// Since: 3.15.0
	Version *int32 `json:"version,omitzero"`

	// Diagnostics An array of diagnostic information items.
	Diagnostics []Diagnostic `json:"diagnostics"`
}

// PublishDiagnosticsClientCapabilities The publish diagnostic client capabilities.
type PublishDiagnosticsClientCapabilities struct {
	DiagnosticsCapabilities

	// VersionSupport Whether the client interprets the version property of the
	// `textDocument/publishDiagnostics` notification's parameter.
	//
	// @since 3.15.0
	//
	// Since: 3.15.0
	VersionSupport *bool `json:"versionSupport,omitzero"`
}
