// Copyright 2024 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by internal/genlsp from metaModel.json; DO NOT EDIT.

package protocol

// DocumentRangeFormattingParams The parameters of a {@link DocumentRangeFormattingRequest}.
type DocumentRangeFormattingParams struct {
	WorkDoneProgressParams

	// TextDocument The document to format.
	TextDocument TextDocumentIdentifier `json:"textDocument"`

	// Range The range to format
	Range Range `json:"range"`

	// Options The format options
	Options FormattingOptions `json:"options"`
}

// DocumentRangeFormattingRegistrationOptions Registration options for a {@link DocumentRangeFormattingRequest}.
type DocumentRangeFormattingRegistrationOptions struct {
	TextDocumentRegistrationOptions
	DocumentRangeFormattingOptions
}

// DocumentRangesFormattingParams The parameters of a {@link DocumentRangesFormattingRequest}.
//
// @since 3.18.0
//
// Since: 3.18.0
type DocumentRangesFormattingParams struct {
	WorkDoneProgressParams

	// TextDocument The document to format.
	TextDocument TextDocumentIdentifier `json:"textDocument"`

	// Ranges The ranges to format
	Ranges []Range `json:"ranges"`

	// Options The format options
	Options FormattingOptions `json:"options"`
}

// DocumentRangeFormattingOptions Provider options for a {@link DocumentRangeFormattingRequest}.
type DocumentRangeFormattingOptions struct {
	WorkDoneProgressOptions

	// RangesSupport Whether the server supports formatting multiple ranges at once.
	//
	// @since 3.18.0
	//
	// Since: 3.18.0
	RangesSupport *bool `json:"rangesSupport,omitzero"`
}

// DocumentRangeFormattingClientCapabilities Client capabilities of a {@link DocumentRangeFormattingRequest}.
type DocumentRangeFormattingClientCapabilities struct {
	// DynamicRegistration Whether range formatting supports dynamic registration.
	DynamicRegistration *bool `json:"dynamicRegistration,omitzero"`

	// RangesSupport Whether the client supports formatting multiple ranges at once.
	//
	// @since 3.18.0
	//
	// Since: 3.18.0
	RangesSupport *bool `json:"rangesSupport,omitzero"`
}
