// Copyright 2026 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by internal/genlsp from metaModel.json; DO NOT EDIT.

package protocol

import (
	"fmt"
	"github.com/go-json-experiment/json/jsontext"
)

// String is a string union arm.
type String string

// Integer is a signed integer union arm.
type Integer int32

// Boolean is a boolean union arm.
type Boolean bool

// LocationSlice is a named type so a []Location arm can satisfy a union interface.
type LocationSlice []Location

// CompletionItemSlice is a named type so a []CompletionItem arm can satisfy a union interface.
type CompletionItemSlice []CompletionItem

// DeclarationLinkSlice is a named type so a []DeclarationLink arm can satisfy a union interface.
type DeclarationLinkSlice []DeclarationLink

// DefinitionLinkSlice is a named type so a []DefinitionLink arm can satisfy a union interface.
type DefinitionLinkSlice []DefinitionLink

// SymbolInformationSlice is a named type so a []SymbolInformation arm can satisfy a union interface.
type SymbolInformationSlice []SymbolInformation

// DocumentSymbolSlice is a named type so a []DocumentSymbol arm can satisfy a union interface.
type DocumentSymbolSlice []DocumentSymbol

// InlineCompletionItemSlice is a named type so a []InlineCompletionItem arm can satisfy a union interface.
type InlineCompletionItemSlice []InlineCompletionItem

// WorkspaceSymbolSlice is a named type so a []WorkspaceSymbol arm can satisfy a union interface.
type WorkspaceSymbolSlice []WorkspaceSymbol

// InlayHintLabelPartSlice is a named type so a []InlayHintLabelPart arm can satisfy a union interface.
type InlayHintLabelPartSlice []InlayHintLabelPart

// StringSlice is a named type so a []string arm can satisfy a union interface.
type StringSlice []string

// MarkedStringSlice is a named type so a []MarkedString arm can satisfy a union interface.
type MarkedStringSlice []MarkedString

// ParameterInformationLabelTuple is a named tuple type for use as a union arm.
type ParameterInformationLabelTuple [2]uint32

// SemanticTokensOptionsRange is a generated inline object literal type.
type SemanticTokensOptionsRange struct {
}

// Definition The definition of a symbol represented as one or many {@link Location locations}.
// For most programming languages there is only one location at which a symbol is
// defined.
//
// Servers should prefer returning `DefinitionLink` over `Definition` if supported
// by the client.
type Declaration interface{ isDeclaration() }

func (*Location) isDeclaration()     {}
func (LocationSlice) isDeclaration() {}

func unmarshalDeclaration(dec *jsontext.Decoder, val *Declaration) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"uri", "range"}, []string{"uri", "range"}) {
			var v Location
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "uri", "range") {
			var v Location
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v Location
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	case '[':
		var v LocationSlice
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	}
	return fmt.Errorf("cannot unmarshal %s into Declaration", raw)
}

// InlineValue Inline value information can be provided by different means:
// - directly as a text value (class InlineValueText).
// - as a name to use for a variable lookup (class InlineValueVariableLookup)
// - as an evaluatable expression (class InlineValueEvaluatableExpression)
// The InlineValue types combines all inline value types into one type.
//
// @since 3.17.0
//
// Since: 3.17.0
type InlineValue interface{ isInlineValue() }

func (*InlineValueText) isInlineValue()                  {}
func (*InlineValueVariableLookup) isInlineValue()        {}
func (*InlineValueEvaluatableExpression) isInlineValue() {}

func unmarshalInlineValue(dec *jsontext.Decoder, val *InlineValue) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"range", "caseSensitiveLookup"}, []string{"range", "variableName", "caseSensitiveLookup"}) {
			var v InlineValueVariableLookup
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"range", "text"}, []string{"range", "text"}) {
			var v InlineValueText
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"range"}, []string{"range", "expression"}) {
			var v InlineValueEvaluatableExpression
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "range", "text") {
			var v InlineValueText
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "range", "caseSensitiveLookup") {
			var v InlineValueVariableLookup
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "range") {
			var v InlineValueEvaluatableExpression
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v InlineValueVariableLookup
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v InlineValueText
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v InlineValueEvaluatableExpression
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into InlineValue", raw)
}

// DocumentDiagnosticReport The result of a document diagnostic pull request. A report can
// either be a full report containing all diagnostics for the
// requested document or an unchanged report indicating that nothing
// has changed in terms of diagnostics in comparison to the last
// pull request.
//
// @since 3.17.0
//
// Since: 3.17.0
type DocumentDiagnosticReport interface{ isDocumentDiagnosticReport() }

func (*RelatedFullDocumentDiagnosticReport) isDocumentDiagnosticReport()      {}
func (*RelatedUnchangedDocumentDiagnosticReport) isDocumentDiagnosticReport() {}

func unmarshalDocumentDiagnosticReport(dec *jsontext.Decoder, val *DocumentDiagnosticReport) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if kv, ok := objectKind(raw); ok {
			switch kv {
			case "full":
				var v RelatedFullDocumentDiagnosticReport
				if err := decodeWith(raw, &v); err != nil {
					return err
				}
				*val = &v
				return nil
			case "unchanged":
				var v RelatedUnchangedDocumentDiagnosticReport
				if err := decodeWith(raw, &v); err != nil {
					return err
				}
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DocumentDiagnosticReport", raw)
}

// PrepareRenameResult is defined by the LSP specification.
type PrepareRenameResult interface{ isPrepareRenameResult() }

func (*Range) isPrepareRenameResult()                        {}
func (*PrepareRenamePlaceholder) isPrepareRenameResult()     {}
func (*PrepareRenameDefaultBehavior) isPrepareRenameResult() {}

func unmarshalPrepareRenameResult(dec *jsontext.Decoder, val *PrepareRenameResult) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"start", "end"}, []string{"start", "end"}) {
			var v Range
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"range", "placeholder"}, []string{"range", "placeholder"}) {
			var v PrepareRenamePlaceholder
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"defaultBehavior"}, []string{"defaultBehavior"}) {
			var v PrepareRenameDefaultBehavior
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "start", "end") {
			var v Range
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "range", "placeholder") {
			var v PrepareRenamePlaceholder
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "defaultBehavior") {
			var v PrepareRenameDefaultBehavior
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v Range
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v PrepareRenamePlaceholder
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v PrepareRenameDefaultBehavior
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into PrepareRenameResult", raw)
}

// ProgressToken is defined by the LSP specification.
type ProgressToken interface{ isProgressToken() }

func (Integer) isProgressToken() {}
func (String) isProgressToken()  {}

func unmarshalProgressToken(dec *jsontext.Decoder, val *ProgressToken) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '0':
		var v Integer
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '"':
		var v String
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	}
	return fmt.Errorf("cannot unmarshal %s into ProgressToken", raw)
}

// WorkspaceDocumentDiagnosticReport A workspace diagnostic document report.
//
// @since 3.17.0
//
// Since: 3.17.0
type WorkspaceDocumentDiagnosticReport interface{ isWorkspaceDocumentDiagnosticReport() }

func (*WorkspaceFullDocumentDiagnosticReport) isWorkspaceDocumentDiagnosticReport()      {}
func (*WorkspaceUnchangedDocumentDiagnosticReport) isWorkspaceDocumentDiagnosticReport() {}

func unmarshalWorkspaceDocumentDiagnosticReport(dec *jsontext.Decoder, val *WorkspaceDocumentDiagnosticReport) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if kv, ok := objectKind(raw); ok {
			switch kv {
			case "full":
				var v WorkspaceFullDocumentDiagnosticReport
				if err := decodeWith(raw, &v); err != nil {
					return err
				}
				*val = &v
				return nil
			case "unchanged":
				var v WorkspaceUnchangedDocumentDiagnosticReport
				if err := decodeWith(raw, &v); err != nil {
					return err
				}
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into WorkspaceDocumentDiagnosticReport", raw)
}

// TextDocumentContentChangeEvent An event describing a change to a text document. If only a text is provided
// it is considered to be the full content of the document.
type TextDocumentContentChangeEvent interface{ isTextDocumentContentChangeEvent() }

func (*TextDocumentContentChangePartial) isTextDocumentContentChangeEvent()       {}
func (*TextDocumentContentChangeWholeDocument) isTextDocumentContentChangeEvent() {}

func unmarshalTextDocumentContentChangeEvent(dec *jsontext.Decoder, val *TextDocumentContentChangeEvent) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"range", "text"}, []string{"range", "rangeLength", "text"}) {
			var v TextDocumentContentChangePartial
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"text"}, []string{"text"}) {
			var v TextDocumentContentChangeWholeDocument
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "range", "text") {
			var v TextDocumentContentChangePartial
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "text") {
			var v TextDocumentContentChangeWholeDocument
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextDocumentContentChangePartial
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextDocumentContentChangeWholeDocument
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into TextDocumentContentChangeEvent", raw)
}

// MarkedString MarkedString can be used to render human readable text. It is either a markdown string
// or a code-block that provides a language and a code snippet. The language identifier
// is semantically equal to the optional language identifier in fenced code blocks in GitHub
// issues. See https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting
//
// The pair of a language and a value is an equivalent to markdown:
// ```${language}
// ${value}
// ```
//
// Note that markdown strings will be sanitized - that means html will be escaped.
// @deprecated use MarkupContent instead.
//
// Deprecated: use MarkupContent instead.
type MarkedString interface{ isMarkedString() }

func (String) isMarkedString()                    {}
func (*MarkedStringWithLanguage) isMarkedString() {}

func unmarshalMarkedString(dec *jsontext.Decoder, val *MarkedString) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '"':
		var v String
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"language", "value"}, []string{"language", "value"}) {
			var v MarkedStringWithLanguage
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "language", "value") {
			var v MarkedStringWithLanguage
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v MarkedStringWithLanguage
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into MarkedString", raw)
}

// DocumentFilter A document filter describes a top level text document or
// a notebook cell document.
//
// @since 3.17.0 - support for NotebookCellTextDocumentFilter.
//
// Since: 3.17.0 - support for NotebookCellTextDocumentFilter.
type DocumentFilter interface{ isDocumentFilter() }

func (*TextDocumentFilterLanguage) isDocumentFilter()     {}
func (*TextDocumentFilterScheme) isDocumentFilter()       {}
func (*TextDocumentFilterPattern) isDocumentFilter()      {}
func (*NotebookCellTextDocumentFilter) isDocumentFilter() {}

func unmarshalDocumentFilter(dec *jsontext.Decoder, val *DocumentFilter) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"language"}, []string{"language", "scheme", "pattern"}) {
			var v TextDocumentFilterLanguage
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"scheme"}, []string{"language", "scheme", "pattern"}) {
			var v TextDocumentFilterScheme
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"pattern"}, []string{"language", "scheme", "pattern"}) {
			var v TextDocumentFilterPattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"notebook"}, []string{"notebook", "language"}) {
			var v NotebookCellTextDocumentFilter
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "language") {
			var v TextDocumentFilterLanguage
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "scheme") {
			var v TextDocumentFilterScheme
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "pattern") {
			var v TextDocumentFilterPattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "notebook") {
			var v NotebookCellTextDocumentFilter
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextDocumentFilterLanguage
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextDocumentFilterScheme
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextDocumentFilterPattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v NotebookCellTextDocumentFilter
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DocumentFilter", raw)
}

// GlobPattern The glob pattern. Either a string pattern or a relative pattern.
//
// @since 3.17.0
//
// Since: 3.17.0
type GlobPattern interface{ isGlobPattern() }

func (Pattern) isGlobPattern()          {}
func (*RelativePattern) isGlobPattern() {}

func unmarshalGlobPattern(dec *jsontext.Decoder, val *GlobPattern) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '"':
		var v Pattern
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"baseUri", "pattern"}, []string{"baseUri", "pattern"}) {
			var v RelativePattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "baseUri", "pattern") {
			var v RelativePattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v RelativePattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into GlobPattern", raw)
}

// TextDocumentFilter A document filter denotes a document by different properties like
// the {@link TextDocument.languageId language}, the {@link Uri.scheme scheme} of
// its resource, or a glob-pattern that is applied to the {@link TextDocument.fileName path}.
//
// Glob patterns can have the following syntax:
// - `*` to match zero or more characters in a path segment
// - `?` to match on one character in a path segment
// - `**` to match any number of path segments, including none
// - `{}` to group sub patterns into an OR expression. (e.g. `**​/*.{ts,js}` matches all TypeScript and JavaScript files)
// - `[]` to declare a range of characters to match in a path segment (e.g., `example.[0-9]` to match on `example.0`, `example.1`, …)
// - `[!...]` to negate a range of characters to match in a path segment (e.g., `example.[!0-9]` to match on `example.a`, `example.b`, but not `example.0`)
//
// @sample A language filter that applies to typescript files on disk: `{ language: 'typescript', scheme: 'file' }`
// @sample A language filter that applies to all package.json paths: `{ language: 'json', pattern: '**package.json' }`
//
// @since 3.17.0
//
// Since: 3.17.0
type TextDocumentFilter interface{ isTextDocumentFilter() }

func (*TextDocumentFilterLanguage) isTextDocumentFilter() {}
func (*TextDocumentFilterScheme) isTextDocumentFilter()   {}
func (*TextDocumentFilterPattern) isTextDocumentFilter()  {}

func unmarshalTextDocumentFilter(dec *jsontext.Decoder, val *TextDocumentFilter) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"language"}, []string{"language", "scheme", "pattern"}) {
			var v TextDocumentFilterLanguage
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"scheme"}, []string{"language", "scheme", "pattern"}) {
			var v TextDocumentFilterScheme
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"pattern"}, []string{"language", "scheme", "pattern"}) {
			var v TextDocumentFilterPattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "language") {
			var v TextDocumentFilterLanguage
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "scheme") {
			var v TextDocumentFilterScheme
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "pattern") {
			var v TextDocumentFilterPattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextDocumentFilterLanguage
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextDocumentFilterScheme
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextDocumentFilterPattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into TextDocumentFilter", raw)
}

// NotebookDocumentFilter A notebook document filter denotes a notebook document by
// different properties. The properties will be match
// against the notebook's URI (same as with documents)
//
// @since 3.17.0
//
// Since: 3.17.0
type NotebookDocumentFilter interface{ isNotebookDocumentFilter() }

func (*NotebookDocumentFilterNotebookType) isNotebookDocumentFilter() {}
func (*NotebookDocumentFilterScheme) isNotebookDocumentFilter()       {}
func (*NotebookDocumentFilterPattern) isNotebookDocumentFilter()      {}

func unmarshalNotebookDocumentFilter(dec *jsontext.Decoder, val *NotebookDocumentFilter) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"notebookType"}, []string{"notebookType", "scheme", "pattern"}) {
			var v NotebookDocumentFilterNotebookType
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"scheme"}, []string{"notebookType", "scheme", "pattern"}) {
			var v NotebookDocumentFilterScheme
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"pattern"}, []string{"notebookType", "scheme", "pattern"}) {
			var v NotebookDocumentFilterPattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "notebookType") {
			var v NotebookDocumentFilterNotebookType
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "scheme") {
			var v NotebookDocumentFilterScheme
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "pattern") {
			var v NotebookDocumentFilterPattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v NotebookDocumentFilterNotebookType
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v NotebookDocumentFilterScheme
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v NotebookDocumentFilterPattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into NotebookDocumentFilter", raw)
}

// CompletionResult is one of: CompletionItemSlice, *CompletionList.
type CompletionResult interface{ isCompletionResult() }

func (CompletionItemSlice) isCompletionResult() {}
func (*CompletionList) isCompletionResult()     {}

func unmarshalCompletionResult(dec *jsontext.Decoder, val *CompletionResult) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '[':
		var v CompletionItemSlice
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"isIncomplete", "items"}, []string{"isIncomplete", "itemDefaults", "applyKind", "items"}) {
			var v CompletionList
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "isIncomplete", "items") {
			var v CompletionList
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v CompletionList
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into CompletionResult", raw)
}

// DeclarationResult is one of: *Location, LocationSlice, DeclarationLinkSlice.
type DeclarationResult interface{ isDeclarationResult() }

func (*Location) isDeclarationResult()            {}
func (LocationSlice) isDeclarationResult()        {}
func (DeclarationLinkSlice) isDeclarationResult() {}

func unmarshalDeclarationResult(dec *jsontext.Decoder, val *DeclarationResult) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"uri", "range"}, []string{"uri", "range"}) {
			var v Location
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "uri", "range") {
			var v Location
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v Location
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	case '[':
		if arrayFirstHasAndKnown(raw, []string{"targetUri", "targetRange", "targetSelectionRange"}, []string{"originSelectionRange", "targetUri", "targetRange", "targetSelectionRange"}) {
			var v DeclarationLinkSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		if arrayFirstHasAndKnown(raw, []string{"uri", "range"}, []string{"uri", "range"}) {
			var v LocationSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		if arrayFirstHasKeys(raw, "targetUri", "targetRange", "targetSelectionRange") {
			var v DeclarationLinkSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		if arrayFirstHasKeys(raw, "uri", "range") {
			var v LocationSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		{
			var v DeclarationLinkSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		{
			var v LocationSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DeclarationResult", raw)
}

// DefinitionResult is one of: *Location, LocationSlice, DefinitionLinkSlice.
type DefinitionResult interface{ isDefinitionResult() }

func (*Location) isDefinitionResult()           {}
func (LocationSlice) isDefinitionResult()       {}
func (DefinitionLinkSlice) isDefinitionResult() {}

func unmarshalDefinitionResult(dec *jsontext.Decoder, val *DefinitionResult) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"uri", "range"}, []string{"uri", "range"}) {
			var v Location
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "uri", "range") {
			var v Location
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v Location
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	case '[':
		if arrayFirstHasAndKnown(raw, []string{"targetUri", "targetRange", "targetSelectionRange"}, []string{"originSelectionRange", "targetUri", "targetRange", "targetSelectionRange"}) {
			var v DefinitionLinkSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		if arrayFirstHasAndKnown(raw, []string{"uri", "range"}, []string{"uri", "range"}) {
			var v LocationSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		if arrayFirstHasKeys(raw, "targetUri", "targetRange", "targetSelectionRange") {
			var v DefinitionLinkSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		if arrayFirstHasKeys(raw, "uri", "range") {
			var v LocationSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		{
			var v DefinitionLinkSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		{
			var v LocationSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DefinitionResult", raw)
}

// DocumentSymbolResult is one of: SymbolInformationSlice, DocumentSymbolSlice.
type DocumentSymbolResult interface{ isDocumentSymbolResult() }

func (SymbolInformationSlice) isDocumentSymbolResult() {}
func (DocumentSymbolSlice) isDocumentSymbolResult()    {}

func unmarshalDocumentSymbolResult(dec *jsontext.Decoder, val *DocumentSymbolResult) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '[':
		if arrayFirstHasAndKnown(raw, []string{"name", "kind", "range", "selectionRange"}, []string{"name", "detail", "kind", "tags", "deprecated", "range", "selectionRange", "children"}) {
			var v DocumentSymbolSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		if arrayFirstHasAndKnown(raw, []string{"location", "name", "kind"}, []string{"deprecated", "location", "name", "kind", "tags", "containerName"}) {
			var v SymbolInformationSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		if arrayFirstHasKeys(raw, "name", "kind", "range", "selectionRange") {
			var v DocumentSymbolSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		if arrayFirstHasKeys(raw, "location", "name", "kind") {
			var v SymbolInformationSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		{
			var v DocumentSymbolSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		{
			var v SymbolInformationSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DocumentSymbolResult", raw)
}

// InlineCompletionResult is one of: *InlineCompletionList, InlineCompletionItemSlice.
type InlineCompletionResult interface{ isInlineCompletionResult() }

func (*InlineCompletionList) isInlineCompletionResult()     {}
func (InlineCompletionItemSlice) isInlineCompletionResult() {}

func unmarshalInlineCompletionResult(dec *jsontext.Decoder, val *InlineCompletionResult) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"items"}, []string{"items"}) {
			var v InlineCompletionList
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "items") {
			var v InlineCompletionList
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v InlineCompletionList
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	case '[':
		var v InlineCompletionItemSlice
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	}
	return fmt.Errorf("cannot unmarshal %s into InlineCompletionResult", raw)
}

// SemanticTokensDeltaResult is one of: *SemanticTokens, *SemanticTokensDelta.
type SemanticTokensDeltaResult interface{ isSemanticTokensDeltaResult() }

func (*SemanticTokens) isSemanticTokensDeltaResult()      {}
func (*SemanticTokensDelta) isSemanticTokensDeltaResult() {}

func unmarshalSemanticTokensDeltaResult(dec *jsontext.Decoder, val *SemanticTokensDeltaResult) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"data"}, []string{"resultId", "data"}) {
			var v SemanticTokens
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"edits"}, []string{"resultId", "edits"}) {
			var v SemanticTokensDelta
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "data") {
			var v SemanticTokens
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "edits") {
			var v SemanticTokensDelta
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v SemanticTokens
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v SemanticTokensDelta
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into SemanticTokensDeltaResult", raw)
}

// WorkspaceSymbolResult is one of: SymbolInformationSlice, WorkspaceSymbolSlice.
type WorkspaceSymbolResult interface{ isWorkspaceSymbolResult() }

func (SymbolInformationSlice) isWorkspaceSymbolResult() {}
func (WorkspaceSymbolSlice) isWorkspaceSymbolResult()   {}

func unmarshalWorkspaceSymbolResult(dec *jsontext.Decoder, val *WorkspaceSymbolResult) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '[':
		if arrayFirstHasAndKnown(raw, []string{"location", "name", "kind"}, []string{"deprecated", "location", "name", "kind", "tags", "containerName"}) {
			var v SymbolInformationSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		if arrayFirstHasAndKnown(raw, []string{"location", "name", "kind"}, []string{"location", "data", "name", "kind", "tags", "containerName"}) {
			var v WorkspaceSymbolSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		if arrayFirstHasKeys(raw, "location", "name", "kind") {
			var v SymbolInformationSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		if arrayFirstHasKeys(raw, "location", "name", "kind") {
			var v WorkspaceSymbolSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		{
			var v SymbolInformationSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
		{
			var v WorkspaceSymbolSlice
			if decodeWith(raw, &v) == nil {
				*val = v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into WorkspaceSymbolResult", raw)
}

// DocumentChange is one of: *TextDocumentEdit, *CreateFile, *RenameFile, *DeleteFile.
type DocumentChange interface{ isDocumentChange() }

func (*TextDocumentEdit) isDocumentChange() {}
func (*CreateFile) isDocumentChange()       {}
func (*RenameFile) isDocumentChange()       {}
func (*DeleteFile) isDocumentChange()       {}

func unmarshalDocumentChange(dec *jsontext.Decoder, val *DocumentChange) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if kv, ok := objectKind(raw); ok {
			switch kv {
			case "create":
				var v CreateFile
				if err := decodeWith(raw, &v); err != nil {
					return err
				}
				*val = &v
				return nil
			case "rename":
				var v RenameFile
				if err := decodeWith(raw, &v); err != nil {
					return err
				}
				*val = &v
				return nil
			case "delete":
				var v DeleteFile
				if err := decodeWith(raw, &v); err != nil {
					return err
				}
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"textDocument", "edits"}, []string{"textDocument", "edits"}) {
			var v TextDocumentEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "textDocument", "edits") {
			var v TextDocumentEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextDocumentEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DocumentChange", raw)
}

// InlayHintLabel is one of: String, InlayHintLabelPartSlice.
type InlayHintLabel interface{ isInlayHintLabel() }

func (String) isInlayHintLabel()                  {}
func (InlayHintLabelPartSlice) isInlayHintLabel() {}

func unmarshalInlayHintLabel(dec *jsontext.Decoder, val *InlayHintLabel) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '"':
		var v String
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '[':
		var v InlayHintLabelPartSlice
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	}
	return fmt.Errorf("cannot unmarshal %s into InlayHintLabel", raw)
}

// InlayHintTooltip is one of: String, *MarkupContent.
type InlayHintTooltip interface{ isInlayHintTooltip() }

func (String) isInlayHintTooltip()         {}
func (*MarkupContent) isInlayHintTooltip() {}

func unmarshalInlayHintTooltip(dec *jsontext.Decoder, val *InlayHintTooltip) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '"':
		var v String
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"kind", "value"}, []string{"kind", "value"}) {
			var v MarkupContent
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "kind", "value") {
			var v MarkupContent
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v MarkupContent
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into InlayHintTooltip", raw)
}

// InlineCompletionItemInsertText is one of: String, *StringValue.
type InlineCompletionItemInsertText interface{ isInlineCompletionItemInsertText() }

func (String) isInlineCompletionItemInsertText()       {}
func (*StringValue) isInlineCompletionItemInsertText() {}

func unmarshalInlineCompletionItemInsertText(dec *jsontext.Decoder, val *InlineCompletionItemInsertText) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '"':
		var v String
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if kv, ok := objectKind(raw); ok {
			switch kv {
			case "snippet":
				var v StringValue
				if err := decodeWith(raw, &v); err != nil {
					return err
				}
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into InlineCompletionItemInsertText", raw)
}

// DidChangeConfigurationRegistrationOptionsSection is one of: String, StringSlice.
type DidChangeConfigurationRegistrationOptionsSection interface{ isDidChangeConfigurationRegistrationOptionsSection() }

func (String) isDidChangeConfigurationRegistrationOptionsSection()      {}
func (StringSlice) isDidChangeConfigurationRegistrationOptionsSection() {}

func unmarshalDidChangeConfigurationRegistrationOptionsSection(dec *jsontext.Decoder, val *DidChangeConfigurationRegistrationOptionsSection) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '"':
		var v String
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '[':
		var v StringSlice
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	}
	return fmt.Errorf("cannot unmarshal %s into DidChangeConfigurationRegistrationOptionsSection", raw)
}

// CompletionItemTextEdit is one of: *TextEdit, *InsertReplaceEdit.
type CompletionItemTextEdit interface{ isCompletionItemTextEdit() }

func (*TextEdit) isCompletionItemTextEdit()          {}
func (*InsertReplaceEdit) isCompletionItemTextEdit() {}

func unmarshalCompletionItemTextEdit(dec *jsontext.Decoder, val *CompletionItemTextEdit) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"newText", "insert", "replace"}, []string{"newText", "insert", "replace"}) {
			var v InsertReplaceEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"range", "newText"}, []string{"range", "newText"}) {
			var v TextEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "newText", "insert", "replace") {
			var v InsertReplaceEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "range", "newText") {
			var v TextEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v InsertReplaceEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into CompletionItemTextEdit", raw)
}

// HoverContents is one of: *MarkupContent, String, *MarkedStringWithLanguage, MarkedStringSlice.
type HoverContents interface{ isHoverContents() }

func (*MarkupContent) isHoverContents()            {}
func (String) isHoverContents()                    {}
func (*MarkedStringWithLanguage) isHoverContents() {}
func (MarkedStringSlice) isHoverContents()         {}

func unmarshalHoverContents(dec *jsontext.Decoder, val *HoverContents) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"kind", "value"}, []string{"kind", "value"}) {
			var v MarkupContent
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"language", "value"}, []string{"language", "value"}) {
			var v MarkedStringWithLanguage
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "kind", "value") {
			var v MarkupContent
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "language", "value") {
			var v MarkedStringWithLanguage
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v MarkupContent
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v MarkedStringWithLanguage
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	case '"':
		var v String
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '[':
		var v MarkedStringSlice
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	}
	return fmt.Errorf("cannot unmarshal %s into HoverContents", raw)
}

// WorkspaceSymbolLocation is one of: *Location, *LocationUriOnly.
type WorkspaceSymbolLocation interface{ isWorkspaceSymbolLocation() }

func (*Location) isWorkspaceSymbolLocation()        {}
func (*LocationUriOnly) isWorkspaceSymbolLocation() {}

func unmarshalWorkspaceSymbolLocation(dec *jsontext.Decoder, val *WorkspaceSymbolLocation) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"uri", "range"}, []string{"uri", "range"}) {
			var v Location
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"uri"}, []string{"uri"}) {
			var v LocationUriOnly
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "uri", "range") {
			var v Location
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "uri") {
			var v LocationUriOnly
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v Location
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v LocationUriOnly
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into WorkspaceSymbolLocation", raw)
}

// SemanticTokensOptionsFull is one of: Boolean, *SemanticTokensFullDelta.
type SemanticTokensOptionsFull interface{ isSemanticTokensOptionsFull() }

func (Boolean) isSemanticTokensOptionsFull()                  {}
func (*SemanticTokensFullDelta) isSemanticTokensOptionsFull() {}

func unmarshalSemanticTokensOptionsFull(dec *jsontext.Decoder, val *SemanticTokensOptionsFull) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "delta") {
			var v SemanticTokensFullDelta
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v SemanticTokensFullDelta
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into SemanticTokensOptionsFull", raw)
}

// TextDocumentEditElement is one of: *TextEdit, *AnnotatedTextEdit, *SnippetTextEdit.
type TextDocumentEditElement interface{ isTextDocumentEditElement() }

func (*TextEdit) isTextDocumentEditElement()          {}
func (*AnnotatedTextEdit) isTextDocumentEditElement() {}
func (*SnippetTextEdit) isTextDocumentEditElement()   {}

func unmarshalTextDocumentEditElement(dec *jsontext.Decoder, val *TextDocumentEditElement) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"annotationId", "range", "newText"}, []string{"annotationId", "range", "newText"}) {
			var v AnnotatedTextEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"range", "snippet"}, []string{"range", "snippet", "annotationId"}) {
			var v SnippetTextEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"range", "newText"}, []string{"range", "newText"}) {
			var v TextEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "annotationId", "range", "newText") {
			var v AnnotatedTextEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "range", "newText") {
			var v TextEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "range", "snippet") {
			var v SnippetTextEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v AnnotatedTextEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v SnippetTextEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextEdit
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into TextDocumentEditElement", raw)
}

// NotebookSelector is one of: *NotebookDocumentFilterWithNotebook, *NotebookDocumentFilterWithCells.
type NotebookSelector interface{ isNotebookSelector() }

func (*NotebookDocumentFilterWithNotebook) isNotebookSelector() {}
func (*NotebookDocumentFilterWithCells) isNotebookSelector()    {}

func unmarshalNotebookSelector(dec *jsontext.Decoder, val *NotebookSelector) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"notebook"}, []string{"notebook", "cells"}) {
			var v NotebookDocumentFilterWithNotebook
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"cells"}, []string{"notebook", "cells"}) {
			var v NotebookDocumentFilterWithCells
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "notebook") {
			var v NotebookDocumentFilterWithNotebook
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "cells") {
			var v NotebookDocumentFilterWithCells
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v NotebookDocumentFilterWithNotebook
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v NotebookDocumentFilterWithCells
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into NotebookSelector", raw)
}

// TextDocumentSync is one of: *TextDocumentSyncOptions, TextDocumentSyncKind.
type TextDocumentSync interface{ isTextDocumentSync() }

func (*TextDocumentSyncOptions) isTextDocumentSync() {}
func (TextDocumentSyncKind) isTextDocumentSync()     {}

func unmarshalTextDocumentSync(dec *jsontext.Decoder, val *TextDocumentSync) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectKeysKnown(raw, "openClose", "change", "willSave", "willSaveWaitUntil", "save") {
			var v TextDocumentSyncOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextDocumentSyncOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	case '0':
		var v TextDocumentSyncKind
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	}
	return fmt.Errorf("cannot unmarshal %s into TextDocumentSync", raw)
}

// NotebookDocumentSync is one of: *NotebookDocumentSyncOptions, *NotebookDocumentSyncRegistrationOptions.
type NotebookDocumentSync interface{ isNotebookDocumentSync() }

func (*NotebookDocumentSyncOptions) isNotebookDocumentSync()             {}
func (*NotebookDocumentSyncRegistrationOptions) isNotebookDocumentSync() {}

func unmarshalNotebookDocumentSync(dec *jsontext.Decoder, val *NotebookDocumentSync) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"notebookSelector"}, []string{"notebookSelector", "save", "id"}) {
			var v NotebookDocumentSyncRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"notebookSelector"}, []string{"notebookSelector", "save"}) {
			var v NotebookDocumentSyncOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "notebookSelector") {
			var v NotebookDocumentSyncOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "notebookSelector") {
			var v NotebookDocumentSyncRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v NotebookDocumentSyncRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v NotebookDocumentSyncOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into NotebookDocumentSync", raw)
}

// HoverProvider is one of: Boolean, *HoverOptions.
type HoverProvider interface{ isHoverProvider() }

func (Boolean) isHoverProvider()       {}
func (*HoverOptions) isHoverProvider() {}

func unmarshalHoverProvider(dec *jsontext.Decoder, val *HoverProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "workDoneProgress") {
			var v HoverOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v HoverOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into HoverProvider", raw)
}

// DeclarationProvider is one of: Boolean, *DeclarationOptions, *DeclarationRegistrationOptions.
type DeclarationProvider interface{ isDeclarationProvider() }

func (Boolean) isDeclarationProvider()                         {}
func (*DeclarationOptions) isDeclarationProvider()             {}
func (*DeclarationRegistrationOptions) isDeclarationProvider() {}

func unmarshalDeclarationProvider(dec *jsontext.Decoder, val *DeclarationProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector"}, []string{"workDoneProgress", "documentSelector", "id"}) {
			var v DeclarationRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectKeysKnown(raw, "workDoneProgress") {
			var v DeclarationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector") {
			var v DeclarationRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v DeclarationRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v DeclarationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DeclarationProvider", raw)
}

// DefinitionProvider is one of: Boolean, *DefinitionOptions.
type DefinitionProvider interface{ isDefinitionProvider() }

func (Boolean) isDefinitionProvider()            {}
func (*DefinitionOptions) isDefinitionProvider() {}

func unmarshalDefinitionProvider(dec *jsontext.Decoder, val *DefinitionProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "workDoneProgress") {
			var v DefinitionOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v DefinitionOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DefinitionProvider", raw)
}

// TypeDefinitionProvider is one of: Boolean, *TypeDefinitionOptions, *TypeDefinitionRegistrationOptions.
type TypeDefinitionProvider interface{ isTypeDefinitionProvider() }

func (Boolean) isTypeDefinitionProvider()                            {}
func (*TypeDefinitionOptions) isTypeDefinitionProvider()             {}
func (*TypeDefinitionRegistrationOptions) isTypeDefinitionProvider() {}

func unmarshalTypeDefinitionProvider(dec *jsontext.Decoder, val *TypeDefinitionProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector"}, []string{"documentSelector", "workDoneProgress", "id"}) {
			var v TypeDefinitionRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectKeysKnown(raw, "workDoneProgress") {
			var v TypeDefinitionOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector") {
			var v TypeDefinitionRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TypeDefinitionRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TypeDefinitionOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into TypeDefinitionProvider", raw)
}

// ImplementationProvider is one of: Boolean, *ImplementationOptions, *ImplementationRegistrationOptions.
type ImplementationProvider interface{ isImplementationProvider() }

func (Boolean) isImplementationProvider()                            {}
func (*ImplementationOptions) isImplementationProvider()             {}
func (*ImplementationRegistrationOptions) isImplementationProvider() {}

func unmarshalImplementationProvider(dec *jsontext.Decoder, val *ImplementationProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector"}, []string{"documentSelector", "workDoneProgress", "id"}) {
			var v ImplementationRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectKeysKnown(raw, "workDoneProgress") {
			var v ImplementationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector") {
			var v ImplementationRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v ImplementationRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v ImplementationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into ImplementationProvider", raw)
}

// ReferencesProvider is one of: Boolean, *ReferenceOptions.
type ReferencesProvider interface{ isReferencesProvider() }

func (Boolean) isReferencesProvider()           {}
func (*ReferenceOptions) isReferencesProvider() {}

func unmarshalReferencesProvider(dec *jsontext.Decoder, val *ReferencesProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "workDoneProgress") {
			var v ReferenceOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v ReferenceOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into ReferencesProvider", raw)
}

// DocumentHighlightProvider is one of: Boolean, *DocumentHighlightOptions.
type DocumentHighlightProvider interface{ isDocumentHighlightProvider() }

func (Boolean) isDocumentHighlightProvider()                   {}
func (*DocumentHighlightOptions) isDocumentHighlightProvider() {}

func unmarshalDocumentHighlightProvider(dec *jsontext.Decoder, val *DocumentHighlightProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "workDoneProgress") {
			var v DocumentHighlightOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v DocumentHighlightOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DocumentHighlightProvider", raw)
}

// DocumentSymbolProvider is one of: Boolean, *DocumentSymbolOptions.
type DocumentSymbolProvider interface{ isDocumentSymbolProvider() }

func (Boolean) isDocumentSymbolProvider()                {}
func (*DocumentSymbolOptions) isDocumentSymbolProvider() {}

func unmarshalDocumentSymbolProvider(dec *jsontext.Decoder, val *DocumentSymbolProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "label", "workDoneProgress") {
			var v DocumentSymbolOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v DocumentSymbolOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DocumentSymbolProvider", raw)
}

// CodeActionProvider is one of: Boolean, *CodeActionOptions.
type CodeActionProvider interface{ isCodeActionProvider() }

func (Boolean) isCodeActionProvider()            {}
func (*CodeActionOptions) isCodeActionProvider() {}

func unmarshalCodeActionProvider(dec *jsontext.Decoder, val *CodeActionProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "codeActionKinds", "documentation", "resolveProvider", "workDoneProgress") {
			var v CodeActionOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v CodeActionOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into CodeActionProvider", raw)
}

// ColorProvider is one of: Boolean, *DocumentColorOptions, *DocumentColorRegistrationOptions.
type ColorProvider interface{ isColorProvider() }

func (Boolean) isColorProvider()                           {}
func (*DocumentColorOptions) isColorProvider()             {}
func (*DocumentColorRegistrationOptions) isColorProvider() {}

func unmarshalColorProvider(dec *jsontext.Decoder, val *ColorProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector"}, []string{"documentSelector", "workDoneProgress", "id"}) {
			var v DocumentColorRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectKeysKnown(raw, "workDoneProgress") {
			var v DocumentColorOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector") {
			var v DocumentColorRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v DocumentColorRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v DocumentColorOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into ColorProvider", raw)
}

// WorkspaceSymbolProvider is one of: Boolean, *WorkspaceSymbolOptions.
type WorkspaceSymbolProvider interface{ isWorkspaceSymbolProvider() }

func (Boolean) isWorkspaceSymbolProvider()                 {}
func (*WorkspaceSymbolOptions) isWorkspaceSymbolProvider() {}

func unmarshalWorkspaceSymbolProvider(dec *jsontext.Decoder, val *WorkspaceSymbolProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "resolveProvider", "workDoneProgress") {
			var v WorkspaceSymbolOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v WorkspaceSymbolOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into WorkspaceSymbolProvider", raw)
}

// DocumentFormattingProvider is one of: Boolean, *DocumentFormattingOptions.
type DocumentFormattingProvider interface{ isDocumentFormattingProvider() }

func (Boolean) isDocumentFormattingProvider()                    {}
func (*DocumentFormattingOptions) isDocumentFormattingProvider() {}

func unmarshalDocumentFormattingProvider(dec *jsontext.Decoder, val *DocumentFormattingProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "workDoneProgress") {
			var v DocumentFormattingOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v DocumentFormattingOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DocumentFormattingProvider", raw)
}

// DocumentRangeFormattingProvider is one of: Boolean, *DocumentRangeFormattingOptions.
type DocumentRangeFormattingProvider interface{ isDocumentRangeFormattingProvider() }

func (Boolean) isDocumentRangeFormattingProvider()                         {}
func (*DocumentRangeFormattingOptions) isDocumentRangeFormattingProvider() {}

func unmarshalDocumentRangeFormattingProvider(dec *jsontext.Decoder, val *DocumentRangeFormattingProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "rangesSupport", "workDoneProgress") {
			var v DocumentRangeFormattingOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v DocumentRangeFormattingOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DocumentRangeFormattingProvider", raw)
}

// RenameProvider is one of: Boolean, *RenameOptions.
type RenameProvider interface{ isRenameProvider() }

func (Boolean) isRenameProvider()        {}
func (*RenameOptions) isRenameProvider() {}

func unmarshalRenameProvider(dec *jsontext.Decoder, val *RenameProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "prepareProvider", "workDoneProgress") {
			var v RenameOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v RenameOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into RenameProvider", raw)
}

// FoldingRangeProvider is one of: Boolean, *FoldingRangeOptions, *FoldingRangeRegistrationOptions.
type FoldingRangeProvider interface{ isFoldingRangeProvider() }

func (Boolean) isFoldingRangeProvider()                          {}
func (*FoldingRangeOptions) isFoldingRangeProvider()             {}
func (*FoldingRangeRegistrationOptions) isFoldingRangeProvider() {}

func unmarshalFoldingRangeProvider(dec *jsontext.Decoder, val *FoldingRangeProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector"}, []string{"documentSelector", "workDoneProgress", "id"}) {
			var v FoldingRangeRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectKeysKnown(raw, "workDoneProgress") {
			var v FoldingRangeOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector") {
			var v FoldingRangeRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v FoldingRangeRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v FoldingRangeOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into FoldingRangeProvider", raw)
}

// SelectionRangeProvider is one of: Boolean, *SelectionRangeOptions, *SelectionRangeRegistrationOptions.
type SelectionRangeProvider interface{ isSelectionRangeProvider() }

func (Boolean) isSelectionRangeProvider()                            {}
func (*SelectionRangeOptions) isSelectionRangeProvider()             {}
func (*SelectionRangeRegistrationOptions) isSelectionRangeProvider() {}

func unmarshalSelectionRangeProvider(dec *jsontext.Decoder, val *SelectionRangeProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector"}, []string{"workDoneProgress", "documentSelector", "id"}) {
			var v SelectionRangeRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectKeysKnown(raw, "workDoneProgress") {
			var v SelectionRangeOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector") {
			var v SelectionRangeRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v SelectionRangeRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v SelectionRangeOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into SelectionRangeProvider", raw)
}

// CallHierarchyProvider is one of: Boolean, *CallHierarchyOptions, *CallHierarchyRegistrationOptions.
type CallHierarchyProvider interface{ isCallHierarchyProvider() }

func (Boolean) isCallHierarchyProvider()                           {}
func (*CallHierarchyOptions) isCallHierarchyProvider()             {}
func (*CallHierarchyRegistrationOptions) isCallHierarchyProvider() {}

func unmarshalCallHierarchyProvider(dec *jsontext.Decoder, val *CallHierarchyProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector"}, []string{"documentSelector", "workDoneProgress", "id"}) {
			var v CallHierarchyRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectKeysKnown(raw, "workDoneProgress") {
			var v CallHierarchyOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector") {
			var v CallHierarchyRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v CallHierarchyRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v CallHierarchyOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into CallHierarchyProvider", raw)
}

// LinkedEditingRangeProvider is one of: Boolean, *LinkedEditingRangeOptions, *LinkedEditingRangeRegistrationOptions.
type LinkedEditingRangeProvider interface{ isLinkedEditingRangeProvider() }

func (Boolean) isLinkedEditingRangeProvider()                                {}
func (*LinkedEditingRangeOptions) isLinkedEditingRangeProvider()             {}
func (*LinkedEditingRangeRegistrationOptions) isLinkedEditingRangeProvider() {}

func unmarshalLinkedEditingRangeProvider(dec *jsontext.Decoder, val *LinkedEditingRangeProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector"}, []string{"documentSelector", "workDoneProgress", "id"}) {
			var v LinkedEditingRangeRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectKeysKnown(raw, "workDoneProgress") {
			var v LinkedEditingRangeOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector") {
			var v LinkedEditingRangeRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v LinkedEditingRangeRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v LinkedEditingRangeOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into LinkedEditingRangeProvider", raw)
}

// SemanticTokensProvider is one of: *SemanticTokensOptions, *SemanticTokensRegistrationOptions.
type SemanticTokensProvider interface{ isSemanticTokensProvider() }

func (*SemanticTokensOptions) isSemanticTokensProvider()             {}
func (*SemanticTokensRegistrationOptions) isSemanticTokensProvider() {}

func unmarshalSemanticTokensProvider(dec *jsontext.Decoder, val *SemanticTokensProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector", "legend"}, []string{"documentSelector", "legend", "range", "full", "workDoneProgress", "id"}) {
			var v SemanticTokensRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"legend"}, []string{"legend", "range", "full", "workDoneProgress"}) {
			var v SemanticTokensOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector", "legend") {
			var v SemanticTokensRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "legend") {
			var v SemanticTokensOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v SemanticTokensRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v SemanticTokensOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into SemanticTokensProvider", raw)
}

// MonikerProvider is one of: Boolean, *MonikerOptions, *MonikerRegistrationOptions.
type MonikerProvider interface{ isMonikerProvider() }

func (Boolean) isMonikerProvider()                     {}
func (*MonikerOptions) isMonikerProvider()             {}
func (*MonikerRegistrationOptions) isMonikerProvider() {}

func unmarshalMonikerProvider(dec *jsontext.Decoder, val *MonikerProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector"}, []string{"documentSelector", "workDoneProgress"}) {
			var v MonikerRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectKeysKnown(raw, "workDoneProgress") {
			var v MonikerOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector") {
			var v MonikerRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v MonikerRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v MonikerOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into MonikerProvider", raw)
}

// TypeHierarchyProvider is one of: Boolean, *TypeHierarchyOptions, *TypeHierarchyRegistrationOptions.
type TypeHierarchyProvider interface{ isTypeHierarchyProvider() }

func (Boolean) isTypeHierarchyProvider()                           {}
func (*TypeHierarchyOptions) isTypeHierarchyProvider()             {}
func (*TypeHierarchyRegistrationOptions) isTypeHierarchyProvider() {}

func unmarshalTypeHierarchyProvider(dec *jsontext.Decoder, val *TypeHierarchyProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector"}, []string{"documentSelector", "workDoneProgress", "id"}) {
			var v TypeHierarchyRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectKeysKnown(raw, "workDoneProgress") {
			var v TypeHierarchyOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector") {
			var v TypeHierarchyRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TypeHierarchyRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TypeHierarchyOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into TypeHierarchyProvider", raw)
}

// InlineValueProvider is one of: Boolean, *InlineValueOptions, *InlineValueRegistrationOptions.
type InlineValueProvider interface{ isInlineValueProvider() }

func (Boolean) isInlineValueProvider()                         {}
func (*InlineValueOptions) isInlineValueProvider()             {}
func (*InlineValueRegistrationOptions) isInlineValueProvider() {}

func unmarshalInlineValueProvider(dec *jsontext.Decoder, val *InlineValueProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector"}, []string{"workDoneProgress", "documentSelector", "id"}) {
			var v InlineValueRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectKeysKnown(raw, "workDoneProgress") {
			var v InlineValueOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector") {
			var v InlineValueRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v InlineValueRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v InlineValueOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into InlineValueProvider", raw)
}

// InlayHintProvider is one of: Boolean, *InlayHintOptions, *InlayHintRegistrationOptions.
type InlayHintProvider interface{ isInlayHintProvider() }

func (Boolean) isInlayHintProvider()                       {}
func (*InlayHintOptions) isInlayHintProvider()             {}
func (*InlayHintRegistrationOptions) isInlayHintProvider() {}

func unmarshalInlayHintProvider(dec *jsontext.Decoder, val *InlayHintProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector"}, []string{"resolveProvider", "workDoneProgress", "documentSelector", "id"}) {
			var v InlayHintRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectKeysKnown(raw, "resolveProvider", "workDoneProgress") {
			var v InlayHintOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector") {
			var v InlayHintRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v InlayHintRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v InlayHintOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into InlayHintProvider", raw)
}

// DiagnosticProvider is one of: *DiagnosticOptions, *DiagnosticRegistrationOptions.
type DiagnosticProvider interface{ isDiagnosticProvider() }

func (*DiagnosticOptions) isDiagnosticProvider()             {}
func (*DiagnosticRegistrationOptions) isDiagnosticProvider() {}

func unmarshalDiagnosticProvider(dec *jsontext.Decoder, val *DiagnosticProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"documentSelector", "interFileDependencies", "workspaceDiagnostics"}, []string{"documentSelector", "identifier", "interFileDependencies", "workspaceDiagnostics", "workDoneProgress", "id"}) {
			var v DiagnosticRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"interFileDependencies", "workspaceDiagnostics"}, []string{"identifier", "interFileDependencies", "workspaceDiagnostics", "workDoneProgress"}) {
			var v DiagnosticOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "documentSelector", "interFileDependencies", "workspaceDiagnostics") {
			var v DiagnosticRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "interFileDependencies", "workspaceDiagnostics") {
			var v DiagnosticOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v DiagnosticRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v DiagnosticOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into DiagnosticProvider", raw)
}

// InlineCompletionProvider is one of: Boolean, *InlineCompletionOptions.
type InlineCompletionProvider interface{ isInlineCompletionProvider() }

func (Boolean) isInlineCompletionProvider()                  {}
func (*InlineCompletionOptions) isInlineCompletionProvider() {}

func unmarshalInlineCompletionProvider(dec *jsontext.Decoder, val *InlineCompletionProvider) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "workDoneProgress") {
			var v InlineCompletionOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v InlineCompletionOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into InlineCompletionProvider", raw)
}

// CompletionItemDefaultsEditRange is one of: *Range, *EditRangeWithInsertReplace.
type CompletionItemDefaultsEditRange interface{ isCompletionItemDefaultsEditRange() }

func (*Range) isCompletionItemDefaultsEditRange()                      {}
func (*EditRangeWithInsertReplace) isCompletionItemDefaultsEditRange() {}

func unmarshalCompletionItemDefaultsEditRange(dec *jsontext.Decoder, val *CompletionItemDefaultsEditRange) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"start", "end"}, []string{"start", "end"}) {
			var v Range
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"insert", "replace"}, []string{"insert", "replace"}) {
			var v EditRangeWithInsertReplace
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "start", "end") {
			var v Range
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "insert", "replace") {
			var v EditRangeWithInsertReplace
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v Range
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v EditRangeWithInsertReplace
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into CompletionItemDefaultsEditRange", raw)
}

// NotebookDocumentFilterNotebook is one of: String, *NotebookDocumentFilterNotebookType, *NotebookDocumentFilterScheme, *NotebookDocumentFilterPattern.
type NotebookDocumentFilterNotebook interface{ isNotebookDocumentFilterNotebook() }

func (String) isNotebookDocumentFilterNotebook()                              {}
func (*NotebookDocumentFilterNotebookType) isNotebookDocumentFilterNotebook() {}
func (*NotebookDocumentFilterScheme) isNotebookDocumentFilterNotebook()       {}
func (*NotebookDocumentFilterPattern) isNotebookDocumentFilterNotebook()      {}

func unmarshalNotebookDocumentFilterNotebook(dec *jsontext.Decoder, val *NotebookDocumentFilterNotebook) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '"':
		var v String
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"notebookType"}, []string{"notebookType", "scheme", "pattern"}) {
			var v NotebookDocumentFilterNotebookType
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"scheme"}, []string{"notebookType", "scheme", "pattern"}) {
			var v NotebookDocumentFilterScheme
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"pattern"}, []string{"notebookType", "scheme", "pattern"}) {
			var v NotebookDocumentFilterPattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "notebookType") {
			var v NotebookDocumentFilterNotebookType
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "scheme") {
			var v NotebookDocumentFilterScheme
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "pattern") {
			var v NotebookDocumentFilterPattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v NotebookDocumentFilterNotebookType
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v NotebookDocumentFilterScheme
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v NotebookDocumentFilterPattern
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into NotebookDocumentFilterNotebook", raw)
}

// TextDocumentSyncOptionsSave is one of: Boolean, *SaveOptions.
type TextDocumentSyncOptionsSave interface{ isTextDocumentSyncOptionsSave() }

func (Boolean) isTextDocumentSyncOptionsSave()      {}
func (*SaveOptions) isTextDocumentSyncOptionsSave() {}

func unmarshalTextDocumentSyncOptionsSave(dec *jsontext.Decoder, val *TextDocumentSyncOptionsSave) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "includeText") {
			var v SaveOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v SaveOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into TextDocumentSyncOptionsSave", raw)
}

// WorkspaceOptionsTextDocumentContent is one of: *TextDocumentContentOptions, *TextDocumentContentRegistrationOptions.
type WorkspaceOptionsTextDocumentContent interface{ isWorkspaceOptionsTextDocumentContent() }

func (*TextDocumentContentOptions) isWorkspaceOptionsTextDocumentContent()             {}
func (*TextDocumentContentRegistrationOptions) isWorkspaceOptionsTextDocumentContent() {}

func unmarshalWorkspaceOptionsTextDocumentContent(dec *jsontext.Decoder, val *WorkspaceOptionsTextDocumentContent) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"schemes"}, []string{"schemes", "id"}) {
			var v TextDocumentContentRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"schemes"}, []string{"schemes"}) {
			var v TextDocumentContentOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "schemes") {
			var v TextDocumentContentOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "schemes") {
			var v TextDocumentContentRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextDocumentContentRegistrationOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v TextDocumentContentOptions
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into WorkspaceOptionsTextDocumentContent", raw)
}

// ParameterInformationLabel is one of: String, ParameterInformationLabelTuple.
type ParameterInformationLabel interface{ isParameterInformationLabel() }

func (String) isParameterInformationLabel()                         {}
func (ParameterInformationLabelTuple) isParameterInformationLabel() {}

func unmarshalParameterInformationLabel(dec *jsontext.Decoder, val *ParameterInformationLabel) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '"':
		var v String
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '[':
		var v ParameterInformationLabelTuple
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	}
	return fmt.Errorf("cannot unmarshal %s into ParameterInformationLabel", raw)
}

// ChangeNotifications is one of: String, Boolean.
type ChangeNotifications interface{ isChangeNotifications() }

func (String) isChangeNotifications()  {}
func (Boolean) isChangeNotifications() {}

func unmarshalChangeNotifications(dec *jsontext.Decoder, val *ChangeNotifications) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '"':
		var v String
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	}
	return fmt.Errorf("cannot unmarshal %s into ChangeNotifications", raw)
}

// RelativePatternBaseURI is one of: *WorkspaceFolder, URI.
type RelativePatternBaseURI interface{ isRelativePatternBaseURI() }

func (*WorkspaceFolder) isRelativePatternBaseURI() {}
func (URI) isRelativePatternBaseURI()              {}

func unmarshalRelativePatternBaseURI(dec *jsontext.Decoder, val *RelativePatternBaseURI) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"uri", "name"}, []string{"uri", "name"}) {
			var v WorkspaceFolder
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "uri", "name") {
			var v WorkspaceFolder
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v WorkspaceFolder
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	case '"':
		var v URI
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	}
	return fmt.Errorf("cannot unmarshal %s into RelativePatternBaseURI", raw)
}

// ClientSemanticTokensRequestOptionsRange is one of: Boolean, *SemanticTokensOptionsRange.
type ClientSemanticTokensRequestOptionsRange interface{ isClientSemanticTokensRequestOptionsRange() }

func (Boolean) isClientSemanticTokensRequestOptionsRange()                     {}
func (*SemanticTokensOptionsRange) isClientSemanticTokensRequestOptionsRange() {}

func unmarshalClientSemanticTokensRequestOptionsRange(dec *jsontext.Decoder, val *ClientSemanticTokensRequestOptionsRange) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		{
			var v SemanticTokensOptionsRange
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into ClientSemanticTokensRequestOptionsRange", raw)
}

// ClientSemanticTokensRequestOptionsFull is one of: Boolean, *ClientSemanticTokensRequestFullDelta.
type ClientSemanticTokensRequestOptionsFull interface{ isClientSemanticTokensRequestOptionsFull() }

func (Boolean) isClientSemanticTokensRequestOptionsFull()                               {}
func (*ClientSemanticTokensRequestFullDelta) isClientSemanticTokensRequestOptionsFull() {}

func unmarshalClientSemanticTokensRequestOptionsFull(dec *jsontext.Decoder, val *ClientSemanticTokensRequestOptionsFull) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case 't', 'f':
		var v Boolean
		if err := decodeWith(raw, &v); err != nil {
			return err
		}
		*val = v
		return nil
	case '{':
		if objectKeysKnown(raw, "delta") {
			var v ClientSemanticTokensRequestFullDelta
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v ClientSemanticTokensRequestFullDelta
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into ClientSemanticTokensRequestOptionsFull", raw)
}

// FullDocumentDiagnosticReportOrUnchangedDocumentDiagnosticReport is one of: *FullDocumentDiagnosticReport, *UnchangedDocumentDiagnosticReport.
type FullDocumentDiagnosticReportOrUnchangedDocumentDiagnosticReport interface{ isFullDocumentDiagnosticReportOrUnchangedDocumentDiagnosticReport() }

func (*FullDocumentDiagnosticReport) isFullDocumentDiagnosticReportOrUnchangedDocumentDiagnosticReport() {
}
func (*UnchangedDocumentDiagnosticReport) isFullDocumentDiagnosticReportOrUnchangedDocumentDiagnosticReport() {
}

func unmarshalFullDocumentDiagnosticReportOrUnchangedDocumentDiagnosticReport(dec *jsontext.Decoder, val *FullDocumentDiagnosticReportOrUnchangedDocumentDiagnosticReport) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if kv, ok := objectKind(raw); ok {
			switch kv {
			case "full":
				var v FullDocumentDiagnosticReport
				if err := decodeWith(raw, &v); err != nil {
					return err
				}
				*val = &v
				return nil
			case "unchanged":
				var v UnchangedDocumentDiagnosticReport
				if err := decodeWith(raw, &v); err != nil {
					return err
				}
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into FullDocumentDiagnosticReportOrUnchangedDocumentDiagnosticReport", raw)
}

// CommandOrCodeAction is one of: *Command, *CodeAction.
type CommandOrCodeAction interface{ isCommandOrCodeAction() }

func (*Command) isCommandOrCodeAction()    {}
func (*CodeAction) isCommandOrCodeAction() {}

func unmarshalCommandOrCodeAction(dec *jsontext.Decoder, val *CommandOrCodeAction) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	switch raw.Kind() {
	case 'n':
		*val = nil
		return nil
	case '{':
		if objectHasAndKnownGuard(raw, []string{"title"}, []string{"title", "kind", "diagnostics", "isPreferred", "disabled", "edit", "command", "data", "tags"}) {
			var v CodeAction
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasAndKnownGuard(raw, []string{"title", "command"}, []string{"title", "tooltip", "command", "arguments"}) {
			var v Command
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "title", "command") {
			var v Command
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		if objectHasKeys(raw, "title") {
			var v CodeAction
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v CodeAction
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
		{
			var v Command
			if decodeWith(raw, &v) == nil {
				*val = &v
				return nil
			}
		}
	}
	return fmt.Errorf("cannot unmarshal %s into CommandOrCodeAction", raw)
}

// ImplementationResult is an alias for DefinitionResult: the two share one result shape.
type ImplementationResult = DefinitionResult

// TypeDefinitionResult is an alias for DefinitionResult: the two share one result shape.
type TypeDefinitionResult = DefinitionResult
