// Copyright 2024 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

// Command genlsp generates the go.lsp.dev/protocol package from the LSP
// meta-model (metaModel.json).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"go.lsp.dev/protocol/internal/genlsp"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genlsp:", err)
		os.Exit(1)
	}
}

func run() error {
	input := flag.String("input", "internal/genlsp/testdata/metaModel.json", "path to metaModel.json")
	output := flag.String("output", ".", "output directory for generated files")
	pkg := flag.String("pkg", "protocol", "generated package name")
	flag.Parse()

	m, err := genlsp.Load(*input)
	if err != nil {
		return err
	}

	g := genlsp.NewGenerator(m, *pkg)
	files, emitErr := g.Emit()

	if err := os.MkdirAll(*output, 0o755); err != nil {
		return err
	}
	// Remove previously generated files so renamed/split outputs do not leave
	// stale duplicates behind (which would cause duplicate-declaration build
	// errors). Hand-written files lack the generated marker and are preserved.
	if entries, derr := os.ReadDir(*output); derr == nil {
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
				continue
			}
			path := filepath.Join(*output, e.Name())
			b, rerr := os.ReadFile(path)
			if rerr != nil || !bytes.Contains(b, []byte("Code generated by internal/genlsp")) {
				continue
			}
			if err := os.Remove(path); err != nil {
				return fmt.Errorf("remove stale %s: %w", path, err)
			}
		}
	}
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		path := filepath.Join(*output, name)
		if err := os.WriteFile(path, files[name], 0o600); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		fmt.Printf("wrote %s (%d bytes)\n", path, len(files[name]))
	}

	for _, w := range g.Warnings() {
		fmt.Fprintln(os.Stderr, "warn:", w)
	}
	return emitErr
}
