// Copyright 2024 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

package genlsp

import (
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const fileHeader = `// Copyright 2026 The Go Language Server Authors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by internal/genlsp from metaModel.json; DO NOT EDIT.

package %s
`

// renderedField is a fully lowered Go struct field.
type renderedField struct {
	Name     string
	Type     string
	JSONName string
	Tag      string
	Doc      string
}

// renderedStruct is a fully lowered Go struct.
type renderedStruct struct {
	Name   string
	Doc    string
	Embeds []string
	Fields []renderedField
}

// renderedSlice is a generated named slice type that can carry streaming JSON
// methods.
type renderedSlice struct {
	Name string
	Elem string
}

type encoderCtx struct {
	g            *Generator
	structByName map[string]*renderedStruct
	zeroHelpers  map[string]bool
	collecting   map[string]bool
}

// Emit analyses the model and returns generated files keyed by output name.
func (g *Generator) Emit() (map[string][]byte, error) {
	// Pre-pass: assign role/context names to anonymous unions before any use
	// site mints a structural AOrB fallback. Priority is alias > result >
	// property; the first registration of a structural shape wins.
	for _, a := range g.model.TypeAliases {
		if _, ok := wellKnownAny(a.Name); ok {
			continue
		}
		if g.orLowersToUnion(a.Type) {
			g.forceUnion(g.nonNullItems(a.Type.Items), a.Name,
				g.docComment(a.Name, a.Documentation, a.Since, a.Deprecated, a.Proposed))
		}
	}
	g.registerResultUnionNames()
	g.registerPropertyUnionNames()

	structs := g.analyzeStructures()
	aliases := g.analyzeAliases()
	enums := g.analyzeEnumerations()

	// Lower message types last so any types reachable only via messages are
	// registered before rendering.
	messages := g.analyzeMessages()

	generatedStructs := g.generatedStructs(structs)

	// Resolve byte-decoder coverage before rendering unions so arm decodes
	// route through the byte walkers where they exist.
	g.byteCtx = g.buildByteDecCtx(generatedStructs, enums, aliases)

	files := map[string][]byte{}
	var firstErr error
	add := func(name, body string) {
		name = generatedFileName(name)
		out, ferr := formatFile(g.pkg, body)
		files[name] = out // raw bytes on error, formatted otherwise
		if ferr != nil && firstErr == nil {
			firstErr = fmt.Errorf("%s: %w", name, ferr)
		}
	}

	// Split structures/enumerations/aliases into one file per spec section
	// (each language feature gets its own file). Cross-cutting generated code
	// stays in dedicated files below.
	type fileParts struct {
		enums   []*renderedEnum
		aliases []*renderedAlias
		structs []*renderedStruct
	}
	parts := map[string]*fileParts{}
	part := func(f string) *fileParts {
		p := parts[f]
		if p == nil {
			p = &fileParts{}
			parts[f] = p
		}
		return p
	}
	for _, e := range enums {
		p := part(fileForType(e.Name))
		p.enums = append(p.enums, e)
	}
	for _, a := range aliases {
		p := part(fileForType(a.Name))
		p.aliases = append(p.aliases, a)
	}
	for _, s := range structs {
		p := part(fileForType(s.Name))
		p.structs = append(p.structs, s)
	}
	for _, name := range orderedTypeFiles() {
		p := parts[name]
		if p == nil {
			continue // no declarations belong to this section
		}
		var body strings.Builder
		body.WriteString(g.renderEnumerations(p.enums))
		body.WriteString(g.renderAliases(p.aliases))
		body.WriteString(g.renderStructures(p.structs))
		add(name, body.String())
	}

	add("types_unions.go", g.renderUnions())
	add("metamodel_messages.go", messages)
	add("marshalers.go", g.renderMarshalers())
	add("decoders.go", g.renderByteDecoders(g.byteCtx))
	add("encoders.go", g.renderEncoders(generatedStructs, aliases))
	return files, firstErr
}

// generatedFileName returns the checked-in file name for generated source.
func generatedFileName(name string) string {
	const suffix = ".gen.go"

	if strings.HasSuffix(name, suffix) {
		return name
	}
	if stem, ok := strings.CutSuffix(name, "_generated.go"); ok {
		return stem + suffix
	}
	if stem, ok := strings.CutSuffix(name, ".go"); ok {
		return stem + suffix
	}
	return name + ".gen"
}

// formatFile assembles a header, auto-detected imports and body, then
// gofmt-formats it.
func formatFile(pkg, body string) ([]byte, error) {
	var b strings.Builder
	fmt.Fprintf(&b, fileHeader, pkg)
	imports := detectImports(body)
	if len(imports) > 0 {
		b.WriteString("\nimport (\n")
		for _, imp := range imports {
			fmt.Fprintf(&b, "\t%q\n", imp)
		}
		b.WriteString(")\n")
	}
	b.WriteString("\n")
	b.WriteString(body)
	src := []byte(b.String())
	out, ferr := format.Source(src)
	if ferr != nil {
		return src, fmt.Errorf("format: %w", ferr)
	}
	return out, nil
}

// detectImports infers the import set from package-qualified identifiers used
// in body. Struct tags (json:"...") use a colon and are not matched.
func detectImports(body string) []string {
	var imports []string
	if strings.Contains(body, "fmt.") {
		imports = append(imports, "fmt")
	}
	if strings.Contains(body, "errors.") {
		imports = append(imports, "errors")
	}
	if strings.Contains(body, "bytes.") {
		imports = append(imports, "bytes")
	}
	if strings.Contains(body, "slices.") {
		imports = append(imports, "slices")
	}
	if strings.Contains(body, "json.") {
		imports = append(imports, "github.com/go-json-experiment/json")
	}
	if strings.Contains(body, "jsontext.") {
		imports = append(imports, "github.com/go-json-experiment/json/jsontext")
	}
	sort.Strings(imports)
	return imports
}

// ---- structures ----

func (g *Generator) analyzeStructures() []*renderedStruct {
	out := make([]*renderedStruct, 0, len(g.model.Structures))
	for _, s := range g.model.Structures {
		rs := &renderedStruct{
			Name: s.Name,
			Doc:  g.docComment(s.Name, s.Documentation, s.Since, s.Deprecated, s.Proposed),
		}
		for _, ref := range append(append([]*Type{}, s.Extends...), s.Mixins...) {
			if ref.Kind == KindReference {
				rs.Embeds = append(rs.Embeds, ref.Name)
			}
		}
		for _, p := range s.Properties {
			rs.Fields = append(rs.Fields, g.renderField(s.Name, p))
		}
		out = append(out, rs)
	}
	// Reorder into spec-document order. The sort is stable, so types within a
	// feature keep their meta-model (reference) order.
	sort.SliceStable(out, func(i, j int) bool { return featureRank(out[i].Name) < featureRank(out[j].Name) })
	return out
}

func (g *Generator) renderField(owner string, p *Property) renderedField {
	fieldName := exportName(p.Name)
	hint := owner + fieldName
	base := g.lower(p.Type, hint)
	nullable := isNullable(p.Type)
	typ, tagExtra := g.decorate(base, p.Optional, nullable)
	if override, ok := hotFieldType(owner, fieldName, base, p.Optional, nullable); ok {
		typ = override
		tagExtra = ",omitzero"
	}
	if hotOptionalField(owner, fieldName, base, p.Optional, nullable) {
		typ = "Optional[" + base + "]"
		tagExtra = ",omitzero"
	}
	tag := p.Name + tagExtra
	return renderedField{
		Name:     fieldName,
		Type:     typ,
		JSONName: p.Name,
		Tag:      tag,
		Doc:      g.fieldDoc(fieldName, p),
	}
}

// decorate applies pointer and omitzero decoration based on optionality and
// nullability, returning the final Go type and the JSON tag suffix.
func (g *Generator) decorate(goType string, optional, nullable bool) (typ, tag string) {
	if optional && nullable {
		// All three wire states (absent / null / value) are distinct; a plain
		// pointer conflates absent and null. Nullable[T] carries all three.
		return "Nullable[" + goType + "]", ",omitzero"
	}
	nilable := strings.HasPrefix(goType, "[]") ||
		strings.HasPrefix(goType, "map[") ||
		strings.HasPrefix(goType, "*") ||
		g.isUnion(goType) ||
		goType == "LSPAny" || goType == "LSPObject" || goType == "LSPArray"
	switch {
	case optional:
		if !nilable && !g.optionalDropsPointer(goType) {
			goType = "*" + goType
		}
		return goType, ",omitzero"
	case nullable:
		if !nilable {
			goType = "*" + goType
		}
		return goType, ""
	default:
		return goType, ""
	}
}

func (g *Generator) isUnion(name string) bool {
	_, ok := g.unionByName[name]
	return ok
}

func (g *Generator) renderStructures(structs []*renderedStruct) string {
	var b strings.Builder
	for _, s := range structs {
		b.WriteString(s.Doc)
		fmt.Fprintf(&b, "type %s struct {\n", s.Name)
		for _, e := range s.Embeds {
			fmt.Fprintf(&b, "\t%s\n", e)
		}
		if len(s.Embeds) > 0 && len(s.Fields) > 0 {
			b.WriteString("\n")
		}
		for i, f := range s.Fields {
			if f.Doc != "" {
				if i > 0 {
					b.WriteString("\n")
				}
				b.WriteString(indent(f.Doc, "\t"))
			}
			fmt.Fprintf(&b, "\t%s %s `json:%q`\n", f.Name, f.Type, f.Tag)
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

// generatedStructs returns every generated struct declaration that can carry
// streaming JSON methods. Broad generated-type coverage is intentional: the
// generator owns ordinary metaModel structures plus synthesized literal and
// "and" structs rendered into types_unions.gen.go, rather than maintaining a
// handwritten hot-type allowlist.
func (g *Generator) generatedStructs(structs []*renderedStruct) []*renderedStruct {
	out := make([]*renderedStruct, 0, len(structs)+len(g.literalOrder)+len(g.andOrder))
	out = append(out, structs...)
	for _, key := range g.literalOrder {
		out = append(out, g.renderedLiteralStruct(g.literals[key]))
	}
	for _, key := range g.andOrder {
		out = append(out, g.renderedAndStruct(g.ands[key]))
	}
	return out
}

func (g *Generator) renderedLiteralStruct(d *literalDecl) *renderedStruct {
	rs := &renderedStruct{
		Name: d.Name,
		Doc:  fmt.Sprintf("// %s is a generated inline object literal type.\n", d.Name),
	}
	for _, p := range d.Lit.Properties {
		rs.Fields = append(rs.Fields, g.renderField(d.Name, p))
	}
	return rs
}

func (g *Generator) renderedAndStruct(d *andDecl) *renderedStruct {
	return &renderedStruct{
		Name:   d.Name,
		Doc:    fmt.Sprintf("// %s merges %s.\n", d.Name, strings.Join(d.Operands, " & ")),
		Embeds: append([]string(nil), d.Operands...),
	}
}

// ---- enumerations ----

type renderedEnum struct {
	Name       string
	Doc        string
	Underlying string
	Values     []renderedEnumValue
	CustomVals bool
}

type renderedEnumValue struct {
	Name    string
	Literal string
	Doc     string
}

func (g *Generator) analyzeEnumerations() []*renderedEnum {
	out := make([]*renderedEnum, 0, len(g.model.Enumerations))
	for _, e := range g.model.Enumerations {
		underlying := "string"
		switch e.Type.Name {
		case BaseInteger:
			underlying = "int32"
		case BaseUinteger:
			underlying = "uint32"
		}
		re := &renderedEnum{
			Name:       e.Name,
			Doc:        g.docComment(e.Name, e.Documentation, e.Since, e.Deprecated, e.Proposed),
			Underlying: underlying,
			CustomVals: e.SupportsCustomValues,
		}
		for _, v := range e.Values {
			re.Values = append(re.Values, renderedEnumValue{
				Name:    e.Name + exportName(v.Name),
				Literal: string(v.Value),
				Doc:     g.fieldDocText(e.Name+exportName(v.Name), v.Documentation, v.Since, v.Deprecated, v.Proposed),
			})
		}
		out = append(out, re)
	}
	sort.SliceStable(out, func(i, j int) bool { return featureRank(out[i].Name) < featureRank(out[j].Name) })
	return out
}

func (g *Generator) renderEnumerations(enums []*renderedEnum) string {
	var b strings.Builder
	for _, e := range enums {
		b.WriteString(e.Doc)
		fmt.Fprintf(&b, "type %s %s\n\n", e.Name, e.Underlying)
		if len(e.Values) == 0 {
			continue
		}
		fmt.Fprintf(&b, "// %s enumeration values.\n", e.Name)
		b.WriteString("const (\n")
		for _, v := range e.Values {
			if v.Doc != "" {
				b.WriteString(indent(v.Doc, "\t"))
			}
			fmt.Fprintf(&b, "\t%s %s = %s\n", v.Name, e.Name, v.Literal)
		}
		b.WriteString(")\n\n")
	}
	return b.String()
}

// ---- aliases ----

type renderedAlias struct {
	Name string
	Doc  string
	Type string
}

func (g *Generator) analyzeAliases() []*renderedAlias {
	var out []*renderedAlias
	for _, a := range g.model.TypeAliases {
		if _, ok := wellKnownAny(a.Name); ok {
			continue // defined by hand in lspany.go
		}
		if g.orLowersToUnion(a.Type) {
			continue // emitted as a sealed-interface union
		}
		out = append(out, &renderedAlias{
			Name: a.Name,
			Doc:  g.docComment(a.Name, a.Documentation, a.Since, a.Deprecated, a.Proposed),
			Type: g.lower(a.Type, a.Name),
		})
	}
	sort.SliceStable(out, func(i, j int) bool { return featureRank(out[i].Name) < featureRank(out[j].Name) })
	return out
}

func (g *Generator) renderAliases(aliases []*renderedAlias) string {
	var b strings.Builder
	for _, a := range aliases {
		b.WriteString(a.Doc)
		fmt.Fprintf(&b, "type %s %s\n\n", a.Name, a.Type)
	}
	return b.String()
}

// ---- unions and synthesized wrappers ----

// forceUnion registers a union under a fixed name (used by union typeAliases).
func (g *Generator) forceUnion(items []*Type, name, doc string) {
	members := make([]*unionMember, 0, len(items))
	for _, it := range items {
		members = append(members, g.member(it, name))
	}
	sig := unionSignature(members)
	if u, ok := g.unions[sig]; ok {
		u.Name = name // prefer the alias name
		if u.Doc == "" {
			u.Doc = doc
		}
		g.unionByName[name] = u
		return
	}
	u := &unionDecl{Name: name, Members: members, Doc: doc}
	g.unions[sig] = u
	g.unionByName[name] = u
	g.unionOrder = append(g.unionOrder, sig)
}

func (g *Generator) renderUnions() string {
	var b strings.Builder

	// Canonical scalar wrappers used by any union arm.
	g.renderScalarWrappers(&b)

	// Named array/map wrappers (stable order by insertion).
	for _, key := range g.arrayOrder {
		d := g.arrayWrap[key]
		fmt.Fprintf(&b, "// %s is a named type so a %s arm can satisfy a union interface.\n", d.Name, d.Element)
		fmt.Fprintf(&b, "type %s %s\n\n", d.Name, d.Element)
	}
	for _, key := range g.tupleOrder {
		d := g.tupleWrap[key]
		fmt.Fprintf(&b, "// %s is a named tuple type for use as a union arm.\n", d.Name)
		fmt.Fprintf(&b, "type %s %s\n\n", d.Name, d.Expr)
	}

	// Synthesized inline-literal structs.
	for _, key := range g.literalOrder {
		d := g.literals[key]
		g.renderLiteralStruct(&b, d)
	}

	// Synthesized and-merge structs.
	for _, key := range g.andOrder {
		d := g.ands[key]
		fmt.Fprintf(&b, "// %s merges %s.\n", d.Name, strings.Join(d.Operands, " & "))
		fmt.Fprintf(&b, "type %s struct {\n", d.Name)
		for _, op := range d.Operands {
			fmt.Fprintf(&b, "\t%s\n", op)
		}
		b.WriteString("}\n\n")
	}

	// Union interfaces, marker methods and decoders (stable order).
	for _, sig := range g.unionOrder {
		u := g.unions[sig]
		g.renderUnion(&b, u)
	}

	// Role-name aliases for shapes shared by several use sites.
	for _, a := range g.unionAliases {
		fmt.Fprintf(&b, "// %s is an alias for %s: the two share one result shape.\n", a.Name, a.Target)
		fmt.Fprintf(&b, "type %s = %s\n\n", a.Name, a.Target)
	}
	return b.String()
}

func (g *Generator) renderScalarWrappers(b *strings.Builder) {
	type w struct {
		name, under, doc string
	}
	defs := []w{
		{"String", "string", "String is a string union arm."},
		{"Integer", "int32", "Integer is a signed integer union arm."},
		{"Uinteger", "uint32", "Uinteger is an unsigned integer union arm."},
		{"Decimal", "float64", "Decimal is a floating-point union arm."},
		{"Boolean", "bool", "Boolean is a boolean union arm."},
	}
	used := map[BaseTypeName]string{
		BaseString: "String", BaseRegExp: "String", BaseInteger: "Integer",
		BaseUinteger: "Uinteger", BaseDecimal: "Decimal", BaseBoolean: "Boolean",
	}
	active := map[string]bool{}
	for bt := range g.scalarUsed {
		if n, ok := used[bt]; ok {
			active[n] = true
		}
	}
	for _, d := range defs {
		if !active[d.name] {
			continue
		}
		fmt.Fprintf(b, "// %s\ntype %s %s\n\n", d.doc, d.name, d.under)
	}
}

func (g *Generator) renderLiteralStruct(b *strings.Builder, d *literalDecl) {
	fmt.Fprintf(b, "// %s is a generated inline object literal type.\n", d.Name)
	fmt.Fprintf(b, "type %s struct {\n", d.Name)
	for i, p := range d.Lit.Properties {
		f := g.renderField(d.Name, p)
		if f.Doc != "" {
			if i > 0 {
				b.WriteString("\n")
			}
			b.WriteString(indent(f.Doc, "\t"))
		}
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", f.Name, f.Type, f.Tag)
	}
	b.WriteString("}\n\n")
}

func (g *Generator) renderUnion(b *strings.Builder, u *unionDecl) {
	marker := "is" + u.Name
	if u.Doc != "" {
		b.WriteString(u.Doc)
	} else {
		fmt.Fprintf(b, "// %s is one of: %s.\n", u.Name, strings.Join(memberGoTypes(u.Members), ", "))
	}
	fmt.Fprintf(b, "type %s interface{ %s() }\n\n", u.Name, marker)
	// Marker methods (dedup receivers).
	seen := map[string]bool{}
	for _, m := range u.Members {
		if seen[m.Receiver] {
			continue
		}
		seen[m.Receiver] = true
		fmt.Fprintf(b, "func (%s) %s() {}\n", m.Receiver, marker)
	}
	b.WriteString("\n")
	g.renderUnionDecoder(b, u)
}

func memberGoTypes(members []*unionMember) []string {
	out := make([]string, len(members))
	for i, m := range members {
		out[i] = m.GoType
	}
	return out
}

// renderUnionDecoder emits the discriminating UnmarshalFrom function.
func (g *Generator) renderUnionDecoder(b *strings.Builder, u *unionDecl) {
	fn := "unmarshal" + u.Name
	fmt.Fprintf(b, "func %s(dec *jsontext.Decoder, val *%s) error {\n", fn, u.Name)
	b.WriteString("\traw, err := dec.ReadValue()\n\tif err != nil {\n\t\treturn err\n\t}\n")
	fmt.Fprintf(b, "\treturn %sValue(raw, val)\n}\n\n", fn)
	fmt.Fprintf(b, "func %sValue(raw jsontext.Value, val *%s) error {\n", fn, u.Name)
	b.WriteString("\tswitch raw.Kind() {\n")

	byToken := map[byte][]*unionMember{}
	var tokenOrder []byte
	for _, m := range u.Members {
		if _, ok := byToken[m.Token]; !ok {
			tokenOrder = append(tokenOrder, m.Token)
		}
		byToken[m.Token] = append(byToken[m.Token], m)
	}

	// null always decodes to a nil interface (dvNullValue rejects trailing
	// content when the value arrives from the root fast path).
	b.WriteString("\tcase 'n':\n\t\t*val = nil\n\t\treturn dvNullValue(raw)\n")

	for _, tok := range tokenOrder {
		members := byToken[tok]
		switch tok {
		case '{':
			b.WriteString("\tcase '{':\n")
			g.renderObjectDispatch(b, u.Name, members)
		case '[':
			b.WriteString("\tcase '[':\n")
			g.renderArrayDispatch(b, u.Name, members)
		case 't':
			b.WriteString("\tcase 't', 'f':\n")
			g.renderScalarDecode(b, members[0])
		case 'n':
			// handled above
		default:
			fmt.Fprintf(b, "\tcase %s:\n", quoteByte(tok))
			g.renderScalarDecode(b, members[0])
			if len(members) > 1 {
				g.warnf("union %s: %d arms share token %s; first wins", u.Name, len(members), quoteByte(tok))
			}
		}
	}
	b.WriteString("\t}\n")
	fmt.Fprintf(b, "\treturn fmt.Errorf(\"cannot unmarshal %%s into %s\", raw)\n", u.Name)
	b.WriteString("}\n\n")
}

func (g *Generator) renderScalarDecode(b *strings.Builder, m *unionMember) {
	base := strings.TrimPrefix(m.Receiver, "*")
	assign := "v"
	if strings.HasPrefix(m.Receiver, "*") {
		assign = "&v"
	}
	if under, ok := scalarWrapperBase[base]; ok {
		fmt.Fprintf(b, "\t\tv, err := dvScalar%s(raw)\n", exportName(under))
		b.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
		if base == under {
			fmt.Fprintf(b, "\t\t*val = %s\n\t\treturn nil\n", assign)
		} else {
			fmt.Fprintf(b, "\t\t*val = %s(v)\n\t\treturn nil\n", base)
		}
		return
	}
	fmt.Fprintf(b, "\t\tvar v %s\n", base)
	if g.byteCtx != nil && g.byteCtx.armByteCovered(m.Receiver) {
		b.WriteString("\t\tif err := v.unmarshalLSPValue(raw); err != nil {\n\t\t\treturn err\n\t\t}\n")
	} else {
		b.WriteString("\t\tif err := decodeWith(raw, &v); err != nil {\n\t\t\treturn err\n\t\t}\n")
	}
	fmt.Fprintf(b, "\t\t*val = %s\n\t\treturn nil\n", assign)
}

// memberDecode returns the concrete type to decode into and the assignment
// expression for an arm (pointer arms store &v, value arms store v).
func memberDecode(m *unionMember) (base, assign string) {
	if strings.HasPrefix(m.Receiver, "*") {
		return m.Receiver[1:], "&v"
	}
	return m.Receiver, "v"
}

// emitAttempt emits one guarded decode-and-assign block at the given tab indent.
// A failed decode falls through to the next attempt; this is how arms that
// differ only by a field's JSON type (e.g. command: string vs object) are
// disambiguated. Arms whose type carries a byte walker decode through it
// directly instead of constructing a decoder.
func (g *Generator) emitAttempt(b *strings.Builder, guard string, m *unionMember) {
	const ind = "\t\t"
	base, assign := memberDecode(m)
	openTok, closeTok := "{", "}"
	if guard != "" {
		openTok = "if " + guard + " {"
	}
	decode := "decodeWith(raw, &v)"
	if g.byteCtx != nil && g.byteCtx.armByteCovered(m.Receiver) {
		decode = "v.unmarshalLSPValue(raw)"
	}
	fmt.Fprintf(b, "%s%s\n%s\tvar v %s\n", ind, openTok, ind, base)
	fmt.Fprintf(b, "%s\tif %s == nil {\n%s\t\t*val = %s\n%s\t\treturn nil\n%s\t}\n%s%s\n",
		ind, decode, ind, assign, ind, ind, ind, closeTok)
}

// renderObjectDispatch emits disambiguation for object arms. A "kind"
// string-literal discriminator is tried first; otherwise arms are tried in
// three decreasingly-precise, decode-error-gated tiers:
//
//  1. required fields present AND every input key is a known field of the arm
//     (ordered widest-first so a superset arm wins over its subset, preventing
//     field loss);
//  2. required fields present (distinguishes arms with identical full key sets
//     but different required sets, e.g. TextDocumentFilter language/scheme/pattern);
//  3. lenient — ignore unknown extra keys (forward compatibility).
func (g *Generator) renderObjectDispatch(b *strings.Builder, union string, members []*unionMember) {
	var kinded, structural []*unionMember
	for _, m := range members {
		if m.KindConst != "" {
			kinded = append(kinded, m)
		} else {
			structural = append(structural, m)
		}
	}
	if len(kinded) > 0 {
		b.WriteString("\t\tif kv, ok := objectKind(raw); ok {\n\t\t\tswitch kv {\n")
		for _, m := range kinded {
			base, assign := memberDecode(m)
			fmt.Fprintf(b, "\t\t\tcase %q:\n", m.KindConst)
			fmt.Fprintf(b, "\t\t\t\tvar v %s\n", base)
			decode := "decodeWith(raw, &v)"
			if g.byteCtx != nil && g.byteCtx.armByteCovered(m.Receiver) {
				decode = "v.unmarshalLSPValue(raw)"
			}
			fmt.Fprintf(b, "\t\t\t\tif err := %s; err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n", decode)
			fmt.Fprintf(b, "\t\t\t\t*val = %s\n\t\t\t\treturn nil\n", assign)
		}
		b.WriteString("\t\t\t}\n\t\t}\n")
	}
	g.warnIdenticalKeys(union, structural)

	byAllKeys := append([]*unionMember(nil), structural...)
	sort.SliceStable(byAllKeys, func(i, j int) bool { return len(byAllKeys[i].AllKeys) > len(byAllKeys[j].AllKeys) })
	for _, m := range byAllKeys {
		guard := objectGuard(m.Required, m.AllKeys)
		if guard == "" {
			continue // no signal; handled by the lenient tier
		}
		g.emitAttempt(b, guard, m)
	}

	byReq := append([]*unionMember(nil), structural...)
	sort.SliceStable(byReq, func(i, j int) bool { return len(byReq[i].Required) > len(byReq[j].Required) })
	for _, m := range byReq {
		if len(m.Required) == 0 {
			continue // would match unconditionally; defer to the lenient tier
		}
		g.emitAttempt(b, fmt.Sprintf("objectHasKeys(raw, %s)", quoteList(m.Required)), m)
	}

	for _, m := range byAllKeys {
		g.emitAttempt(b, "", m)
	}
}

// renderArrayDispatch mirrors renderObjectDispatch on the first array element.
func (g *Generator) renderArrayDispatch(b *strings.Builder, union string, members []*unionMember) {
	if len(members) == 1 {
		g.renderScalarDecode(b, members[0])
		return
	}
	g.warnIdenticalElemKeys(union, members)

	byAllKeys := append([]*unionMember(nil), members...)
	sort.SliceStable(byAllKeys, func(i, j int) bool { return len(byAllKeys[i].ElemAllKeys) > len(byAllKeys[j].ElemAllKeys) })
	for _, m := range byAllKeys {
		guard := arrayGuard(m.ElemRequired, m.ElemAllKeys)
		if guard == "" {
			continue
		}
		g.emitAttempt(b, guard, m)
	}

	byReq := append([]*unionMember(nil), members...)
	sort.SliceStable(byReq, func(i, j int) bool { return len(byReq[i].ElemRequired) > len(byReq[j].ElemRequired) })
	for _, m := range byReq {
		if len(m.ElemRequired) == 0 {
			continue
		}
		g.emitAttempt(b, fmt.Sprintf("arrayFirstHasKeys(raw, %s)", quoteList(m.ElemRequired)), m)
	}

	for _, m := range byAllKeys {
		g.emitAttempt(b, "", m)
	}
}

// warnIdenticalKeys reports object arms that cannot be distinguished structurally
// because BOTH their required and full key sets are identical (an inherent
// untagged-union ambiguity; arms differing only by required key, or by a field's
// type, are still distinguishable and are not reported).
func (g *Generator) warnIdenticalKeys(union string, members []*unionMember) {
	seen := map[string]string{}
	for _, m := range members {
		sig := keySetSignature(m.Required) + "||" + keySetSignature(m.AllKeys)
		if prev, ok := seen[sig]; ok {
			g.warnf("union %s: object arms %s and %s are structurally identical {req=%s, all=%s}; first declared wins",
				union, prev, m.Receiver, keySetSignature(m.Required), keySetSignature(m.AllKeys))
			continue
		}
		seen[sig] = m.Receiver
	}
}

// warnIdenticalElemKeys is warnIdenticalKeys for array arms' element types.
func (g *Generator) warnIdenticalElemKeys(union string, members []*unionMember) {
	seen := map[string]string{}
	for _, m := range members {
		if len(m.ElemAllKeys) == 0 {
			continue
		}
		sig := keySetSignature(m.ElemRequired) + "||" + keySetSignature(m.ElemAllKeys)
		if prev, ok := seen[sig]; ok {
			g.warnf("union %s: array arms %s and %s have structurally identical elements {req=%s, all=%s}; first declared wins",
				union, prev, m.Receiver, keySetSignature(m.ElemRequired), keySetSignature(m.ElemAllKeys))
			continue
		}
		seen[sig] = m.Receiver
	}
}

// renderMarshalers wires every union decoder into a single Unmarshalers set.
func (g *Generator) renderMarshalers() string {
	var b strings.Builder
	names := make([]string, 0, len(g.unions))
	for _, sig := range g.unionOrder {
		names = append(names, g.unions[sig].Name)
	}
	sort.Strings(names)
	// Assigned in init (not a var initializer) so the static dependency cycle
	// unionUnmarshalers -> unmarshalX -> decodeWith -> unionUnmarshalers is
	// broken: init runs after package-level variable initialization.
	b.WriteString("// unionUnmarshalers dispatches JSON decoding for every generated union type.\n")
	b.WriteString("var unionUnmarshalers *json.Unmarshalers\n\n")
	b.WriteString("func init() {\n\tunionUnmarshalers = json.JoinUnmarshalers(\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t\tjson.UnmarshalFromFunc(unmarshal%s),\n", n)
	}
	b.WriteString("\t)\n}\n")
	return b.String()
}

var hotOptionalFields = map[string]map[string]bool{
	"CompletionItem": {
		"Detail":       true,
		"Deprecated":   true,
		"Preselect":    true,
		"SortText":     true,
		"FilterText":   true,
		"InsertText":   true,
		"TextEditText": true,
	},
	"Diagnostic": {
		"Source": true,
	},
	"PublishDiagnosticsParams": {
		"Version": true,
	},
}

func hotOptionalField(owner, fieldName, base string, optional, nullable bool) bool {
	if !optional || nullable {
		return false
	}
	if base != "string" && base != "bool" && base != "int32" {
		return false
	}
	fields := hotOptionalFields[owner]
	return fields[fieldName]
}

func hotFieldType(owner, fieldName, base string, optional, nullable bool) (string, bool) {
	if owner == "Diagnostic" && fieldName == "Tags" && base == "[]DiagnosticTag" && optional && !nullable {
		return "DiagnosticTags", true
	}
	return "", false
}

func (g *Generator) renderEncoders(structs []*renderedStruct, aliases []*renderedAlias) string {
	selected := make([]*renderedStruct, 0, len(structs))
	ctx := &encoderCtx{
		g:            g,
		structByName: make(map[string]*renderedStruct, len(structs)),
		zeroHelpers:  map[string]bool{},
		collecting:   map[string]bool{},
	}
	for _, s := range structs {
		ctx.structByName[s.Name] = s
		selected = append(selected, s)
	}
	sort.Slice(selected, func(i, j int) bool { return selected[i].Name < selected[j].Name })
	for _, s := range selected {
		ctx.collectZeroHelpersForStruct(s)
	}

	var b strings.Builder
	for _, s := range selected {
		g.renderStructEncoder(ctx, &b, s)
	}
	for _, s := range g.generatedSliceTypes(aliases) {
		g.renderNamedSliceEncoder(&b, s)
	}
	ctx.renderZeroHelpers(&b)
	return b.String()
}

func (g *Generator) generatedSliceTypes(aliases []*renderedAlias) []renderedSlice {
	seen := map[string]bool{}
	var out []renderedSlice
	add := func(name, typ string) {
		elem, ok := strings.CutPrefix(typ, "[]")
		if !ok || seen[name] {
			return
		}
		seen[name] = true
		out = append(out, renderedSlice{Name: name, Elem: elem})
	}
	for _, a := range aliases {
		add(a.Name, a.Type)
	}
	for _, key := range g.arrayOrder {
		d := g.arrayWrap[key]
		add(d.Name, d.Element)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// renderNamedSliceEncoder emits streaming encoders for generated named slice
// types. Most element shapes delegate to json.MarshalEncode so union/scalar
// aliases keep their existing semantics; measured special cases can be kept
// explicit here without reintroducing a broad struct allowlist.
func (g *Generator) renderNamedSliceEncoder(b *strings.Builder, s renderedSlice) {
	fmt.Fprintf(b, "func (x %s) MarshalJSONTo(enc *jsontext.Encoder) error {\n", s.Name)
	b.WriteString("\tif err := enc.WriteToken(jsontext.BeginArray); err != nil {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tfor _, v := range x {\n")
	if s.Name == "WorkspaceSymbolSlice" {
		b.WriteString("\t\tif err := encodeWorkspaceSymbolTo(enc, &v); err != nil {\n")
	} else {
		b.WriteString("\t\tif err := json.MarshalEncode(enc, v); err != nil {\n")
	}
	b.WriteString("\t\t\treturn err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn enc.WriteToken(jsontext.EndArray)\n")
	b.WriteString("}\n\n")
}

func (g *Generator) renderStructEncoder(ctx *encoderCtx, b *strings.Builder, s *renderedStruct) {
	fmt.Fprintf(b, "func (x %s) MarshalJSONTo(enc *jsontext.Encoder) error {\n", s.Name)
	b.WriteString("\tif err := enc.WriteToken(jsontext.BeginObject); err != nil {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	for _, f := range flattenJSONFields(ctx.structByName, s, map[string]bool{}) {
		g.renderFieldEncoder(ctx, b, &f)
	}
	b.WriteString("\treturn enc.WriteToken(jsontext.EndObject)\n")
	b.WriteString("}\n\n")
}

// flattenJSONFields returns the JSON-visible fields of s after recursively
// promoting embedded struct fields and applying the same duplicate-name
// dominance rule as Go's encoding/json field selection: later/local fields
// replace earlier promoted fields with the same JSON name. Encoders and byte
// decoders both use this helper so their embedded-field behavior stays
// symmetric.
func flattenJSONFields(structByName map[string]*renderedStruct, s *renderedStruct, seen map[string]bool) []renderedField {
	if s == nil || seen[s.Name] {
		return nil
	}
	seen[s.Name] = true
	defer delete(seen, s.Name)

	var out []renderedField
	for _, e := range s.Embeds {
		for _, f := range flattenJSONFields(structByName, structByName[e], seen) {
			out = appendJSONField(out, &f)
		}
	}
	for _, f := range s.Fields {
		out = appendJSONField(out, &f)
	}
	return out
}

func appendJSONField(fields []renderedField, f *renderedField) []renderedField {
	for i := range fields {
		if fields[i].JSONName == f.JSONName {
			copy(fields[i:], fields[i+1:])
			fields = fields[:len(fields)-1]
			break
		}
	}
	return append(fields, *f)
}

func (g *Generator) renderFieldEncoder(ctx *encoderCtx, b *strings.Builder, f *renderedField) {
	if f.Type == "Optional[string]" {
		fmt.Fprintf(b, "\tif v, ok := x.%s.Get(); ok {\n", f.Name)
		writeEncoderName(b, f.JSONName, "\t\t")
		b.WriteString("\t\tif err := enc.WriteToken(jsontext.String(v)); err != nil {\n")
		b.WriteString("\t\t\treturn err\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
		return
	}
	if f.Type == "Optional[bool]" {
		fmt.Fprintf(b, "\tif v, ok := x.%s.Get(); ok {\n", f.Name)
		writeEncoderName(b, f.JSONName, "\t\t")
		b.WriteString("\t\tif err := enc.WriteToken(jsontext.Bool(v)); err != nil {\n")
		b.WriteString("\t\t\treturn err\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
		return
	}
	if f.Type == "Optional[int32]" {
		fmt.Fprintf(b, "\tif v, ok := x.%s.Get(); ok {\n", f.Name)
		writeEncoderName(b, f.JSONName, "\t\t")
		b.WriteString("\t\tif err := enc.WriteToken(jsontext.Int(int64(v))); err != nil {\n")
		b.WriteString("\t\t\treturn err\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
		return
	}

	cond := ctx.fieldEncodeCondition(f)
	if cond != "" {
		fmt.Fprintf(b, "\tif %s {\n", cond)
		writeEncoderName(b, f.JSONName, "\t\t")
		writeEncoderValue(ctx, b, f, "\t\t", true)
		b.WriteString("\t}\n")
		return
	}
	writeEncoderName(b, f.JSONName, "\t")
	writeEncoderValue(ctx, b, f, "\t", false)
}

// encodeGuardByType maps an omitzero field type to the Go expression template
// guarding its emission, keyed exactly; prefix-shaped types (pointers, slices,
// maps) are handled structurally in fieldEncodeCondition.
//
//nolint:gosec // G101: Go expression templates for the generator, not credentials.
var encodeGuardByType = map[string]string{
	"LSPAny":                 "len(x.%s) > 0",
	"LSPObject":              "len(x.%s) > 0",
	"LSPArray":               "len(x.%s) > 0",
	"DiagnosticTags":         "!x.%s.IsZero()",
	"CompletionItemTextEdit": "x.%s != nil",
	"InlayHintTooltip":       "x.%s != nil",
	"ProgressToken":          "x.%s != nil",
	"CompletionItemKind":     "x.%s != 0",
	"DiagnosticSeverity":     "x.%s != 0",
	"InsertTextFormat":       "x.%s != 0",
	"InsertTextMode":         "x.%s != 0",
	"uint32":                 "x.%s != 0",
	"int32":                  "x.%s != 0",
	"CodeDescription":        "x.%s != (CodeDescription{})",
	"Command":                "!isZeroCommand(x.%s)",
}

func (c *encoderCtx) fieldEncodeCondition(f *renderedField) string {
	if !strings.Contains(f.Tag, ",omitzero") {
		return ""
	}
	expr := "x." + f.Name
	switch {
	case strings.HasPrefix(f.Type, "Optional["), strings.HasPrefix(f.Type, "Nullable["):
		return "!" + expr + ".IsZero()"
	case strings.HasPrefix(f.Type, "*"):
		return expr + " != nil"
	case strings.HasPrefix(f.Type, "[]"), strings.HasPrefix(f.Type, "map["):
		return "len(" + expr + ") > 0"
	case c.g.isUnion(f.Type):
		return expr + " != nil"
	}
	if tmpl, ok := encodeGuardByType[f.Type]; ok {
		return fmt.Sprintf(tmpl, f.Name)
	}
	if guard, ok := c.scalarNonZeroGuard(f.Type, expr); ok {
		return guard
	}
	if c.zeroHelpers[f.Type] {
		return fmt.Sprintf("!%s(%s)", zeroHelperName(f.Type), expr)
	}
	return "isZeroOmitValue(" + expr + ") == false"
}

func (c *encoderCtx) collectZeroHelpersForStruct(s *renderedStruct) {
	for _, f := range flattenJSONFields(c.structByName, s, map[string]bool{}) {
		if !strings.Contains(f.Tag, ",omitzero") {
			continue
		}
		c.collectZeroHelperType(f.Type)
	}
}

func (c *encoderCtx) collectZeroHelperType(t string) {
	switch {
	case t == "",
		strings.HasPrefix(t, "*"),
		strings.HasPrefix(t, "[]"),
		strings.HasPrefix(t, "map["),
		strings.HasPrefix(t, "Optional["),
		strings.HasPrefix(t, "Nullable["),
		c.g.isUnion(t):
		return
	}
	if _, ok := encodeGuardByType[t]; ok {
		return
	}
	if _, ok := c.scalarNonZeroGuard(t, ""); ok {
		return
	}
	s := c.structByName[t]
	if s == nil || c.zeroHelpers[t] || c.collecting[t] {
		return
	}
	c.collecting[t] = true
	defer delete(c.collecting, t)
	c.zeroHelpers[t] = true
	for _, e := range s.Embeds {
		c.collectZeroHelperType(e)
	}
	for _, f := range s.Fields {
		c.collectZeroHelperType(f.Type)
	}
}

func (c *encoderCtx) renderZeroHelpers(b *strings.Builder) {
	names := make([]string, 0, len(c.zeroHelpers))
	for name := range c.zeroHelpers {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		s := c.structByName[name]
		if s == nil {
			continue
		}
		fmt.Fprintf(b, "func %s(x %s) bool {\n", zeroHelperName(name), name)
		checks := make([]string, 0, len(s.Embeds)+len(s.Fields))
		for _, e := range s.Embeds {
			checks = append(checks, c.zeroExpr(e, "x."+e))
		}
		for _, f := range s.Fields {
			checks = append(checks, c.zeroExpr(f.Type, "x."+f.Name))
		}
		if len(checks) == 0 {
			b.WriteString("\treturn true\n")
		} else {
			b.WriteString("\treturn ")
			b.WriteString(strings.Join(checks, " &&\n\t\t"))
			b.WriteString("\n")
		}
		b.WriteString("}\n\n")
	}
}

func zeroHelperName(name string) string {
	return "isZeroGenerated" + exportName(name)
}

func (c *encoderCtx) zeroExpr(t, expr string) string {
	switch {
	case strings.HasPrefix(t, "Optional["), strings.HasPrefix(t, "Nullable["):
		return expr + ".IsZero()"
	case strings.HasPrefix(t, "*"):
		return expr + " == nil"
	case strings.HasPrefix(t, "[]"), strings.HasPrefix(t, "map["):
		return "len(" + expr + ") == 0"
	case c.g.isUnion(t):
		return expr + " == nil"
	}
	switch t {
	case "LSPAny", "LSPObject", "LSPArray":
		return "len(" + expr + ") == 0"
	case "DiagnosticTags":
		return expr + ".IsZero()"
	case "Command":
		return "isZeroCommand(" + expr + ")"
	case "CodeDescription":
		return expr + " == (CodeDescription{})"
	}
	if guard, ok := c.scalarZeroGuard(t, expr); ok {
		return guard
	}
	if c.zeroHelpers[t] {
		return fmt.Sprintf("%s(%s)", zeroHelperName(t), expr)
	}
	return "isZeroOmitValue(" + expr + ")"
}

func (c *encoderCtx) scalarNonZeroGuard(t, expr string) (string, bool) {
	switch c.scalarBase(t) {
	case "string":
		return expr + ` != ""`, true
	case "bool":
		return expr, true
	case "int32", "uint32", "float64":
		return expr + " != 0", true
	default:
		return "", false
	}
}

func (c *encoderCtx) scalarZeroGuard(t, expr string) (string, bool) {
	switch c.scalarBase(t) {
	case "string":
		return expr + ` == ""`, true
	case "bool":
		return "!" + expr, true
	case "int32", "uint32", "float64":
		return expr + " == 0", true
	default:
		return "", false
	}
}

func (c *encoderCtx) scalarBase(t string) string {
	for range 8 {
		switch t {
		case "string", "int32", "uint32", "float64", "bool":
			return t
		case "URI", "DocumentURI", "String":
			return "string"
		case "Integer":
			return "int32"
		case "Uinteger":
			return "uint32"
		case "Decimal":
			return "float64"
		case "Boolean":
			return "bool"
		}
		if e, ok := c.g.enums[t]; ok {
			return scalarBaseName(e.Type.Name)
		}
		if a, ok := c.g.aliases[t]; ok {
			next := c.scalarBaseFromType(a.Type)
			if next == "" || next == t {
				return next
			}
			t = next
			continue
		}
		return ""
	}
	return ""
}

func (c *encoderCtx) scalarBaseFromType(t *Type) string {
	if t == nil {
		return ""
	}
	switch t.Kind {
	case KindBase:
		return scalarBaseName(BaseTypeName(t.Name))
	case KindReference:
		return c.scalarBase(t.Name)
	default:
		return ""
	}
}

func scalarBaseName(name BaseTypeName) string {
	switch name {
	case BaseString, BaseURI, BaseDocumentURI, BaseRegExp:
		return "string"
	case BaseInteger:
		return "int32"
	case BaseUinteger:
		return "uint32"
	case BaseDecimal:
		return "float64"
	case BaseBoolean:
		return "bool"
	default:
		return ""
	}
}

func writeEncoderName(b *strings.Builder, name, indent string) {
	fmt.Fprintf(b, "%sif err := enc.WriteToken(jsontext.String(%q)); err != nil {\n", indent, name)
	fmt.Fprintf(b, "%s\treturn err\n", indent)
	fmt.Fprintf(b, "%s}\n", indent)
}

func writeEncoderValue(ctx *encoderCtx, b *strings.Builder, f *renderedField, indent string, guarded bool) {
	switch f.Type {
	case "string":
		fmt.Fprintf(b, "%sif err := enc.WriteToken(jsontext.String(x.%s)); err != nil {\n", indent, f.Name)
	case "URI", "DocumentURI":
		fmt.Fprintf(b, "%sif err := enc.WriteToken(jsontext.String(string(x.%s))); err != nil {\n", indent, f.Name)
	case "Position":
		fmt.Fprintf(b, "%sif err := encodePositionTo(enc, x.%s); err != nil {\n", indent, f.Name)
	case "Range":
		fmt.Fprintf(b, "%sif err := encodeRangeTo(enc, x.%s); err != nil {\n", indent, f.Name)
	case "CompletionItemKind", "DiagnosticSeverity", "InsertTextFormat", "InsertTextMode", "uint32":
		fmt.Fprintf(b, "%sif err := enc.WriteToken(jsontext.Uint(uint64(x.%s))); err != nil {\n", indent, f.Name)
	case "int32":
		fmt.Fprintf(b, "%sif err := enc.WriteToken(jsontext.Int(int64(x.%s))); err != nil {\n", indent, f.Name)
	case "InlayHintTooltip":
		fmt.Fprintf(b, "%sif v, ok := x.%s.(String); ok {\n", indent, f.Name)
		fmt.Fprintf(b, "%s\tif err := enc.WriteToken(jsontext.String(string(v))); err != nil {\n", indent)
		fmt.Fprintf(b, "%s\t\treturn err\n", indent)
		fmt.Fprintf(b, "%s\t}\n", indent)
		fmt.Fprintf(b, "%s} else if v, ok := x.%s.(*String); ok {\n", indent, f.Name)
		fmt.Fprintf(b, "%s\tif v == nil {\n", indent)
		fmt.Fprintf(b, "%s\t\treturn enc.WriteToken(jsontext.Null)\n", indent)
		fmt.Fprintf(b, "%s\t}\n", indent)
		fmt.Fprintf(b, "%s\tif err := enc.WriteToken(jsontext.String(string(*v))); err != nil {\n", indent)
		fmt.Fprintf(b, "%s\t\treturn err\n", indent)
		fmt.Fprintf(b, "%s\t}\n", indent)
		fmt.Fprintf(b, "%s} else if err := json.MarshalEncode(enc, x.%s); err != nil {\n", indent, f.Name)
		fmt.Fprintf(b, "%s\treturn err\n", indent)
		fmt.Fprintf(b, "%s}\n", indent)
		return
	case "ProgressToken":
		fmt.Fprintf(b, "%sif err := encodeProgressTokenTo(enc, x.%s); err != nil {\n", indent, f.Name)
	case "DiagnosticTags":
		fmt.Fprintf(b, "%sif err := encodeDiagnosticTagsTo(enc, x.%s); err != nil {\n", indent, f.Name)
	case "LSPAny":
		fmt.Fprintf(b, "%sif err := enc.WriteValue(x.%s); err != nil {\n", indent, f.Name)
	default:
		if !ctx.directStructEncode(b, f, indent, guarded) {
			fmt.Fprintf(b, "%sif err := json.MarshalEncode(enc, x.%s); err != nil {\n", indent, f.Name)
		}
	}
	fmt.Fprintf(b, "%s\treturn err\n", indent)
	fmt.Fprintf(b, "%s}\n", indent)
}

func (c *encoderCtx) directStructEncode(b *strings.Builder, f *renderedField, indent string, guarded bool) bool {
	switch {
	case c.structByName[f.Type] != nil:
		fmt.Fprintf(b, "%sif err := x.%s.MarshalJSONTo(enc); err != nil {\n", indent, f.Name)
		return true
	case strings.HasPrefix(f.Type, "*") && guarded:
		base := strings.TrimPrefix(f.Type, "*")
		if c.structByName[base] != nil {
			fmt.Fprintf(b, "%sif err := x.%s.MarshalJSONTo(enc); err != nil {\n", indent, f.Name)
			return true
		}
	}
	return false
}

// ---- messages ----

func (g *Generator) analyzeMessages() string {
	var b strings.Builder
	type msg struct {
		constName  string
		method     string
		direction  MessageDirection
		kind       string
		params     string
		result     string
		doc        string
		deprecated string
	}
	msgs := make([]msg, 0, len(g.model.Requests)+len(g.model.Notifications))

	for _, r := range g.model.Requests {
		m := msg{
			constName: methodConstName(r.Method), method: r.Method,
			direction: r.MessageDirection, kind: "request",
			params: g.paramsType(r.Params, r.Method+"Params"),
			result: g.lowerOrNil(r.Result, r.Method+"Result"),
			doc:    r.Documentation, deprecated: r.Deprecated,
		}
		msgs = append(msgs, m)
	}
	for _, n := range g.model.Notifications {
		m := msg{
			constName: methodConstName(n.Method), method: n.Method,
			direction: n.MessageDirection, kind: "notification",
			params: g.paramsType(n.Params, n.Method+"Params"),
			doc:    n.Documentation, deprecated: n.Deprecated,
		}
		msgs = append(msgs, m)
	}
	// Order messages by spec-document feature; uncategorized methods (rank 0)
	// sort last. The sort is stable, preserving meta-model order within a feature.
	mrank := func(m string) int {
		if r := methodRank[m]; r != 0 {
			return r
		}
		return len(specFeatures) + 1
	}
	sort.SliceStable(msgs, func(i, j int) bool { return mrank(msgs[i].method) < mrank(msgs[j].method) })

	b.WriteString("// MessageDirection indicates in which direction a message is sent.\n")
	b.WriteString("type MessageDirection string\n\n")
	b.WriteString("// Message directions.\nconst (\n")
	b.WriteString("\tDirectionClientToServer MessageDirection = \"clientToServer\"\n")
	b.WriteString("\tDirectionServerToClient MessageDirection = \"serverToClient\"\n")
	b.WriteString("\tDirectionBoth MessageDirection = \"both\"\n)\n\n")

	b.WriteString("// LSP method names.\nconst (\n")
	for i := range msgs {
		m := &msgs[i]
		if m.doc != "" {
			fmt.Fprintf(&b, "\t// %s is the %q %s method.\n", m.constName, m.method, m.kind)
		}
		fmt.Fprintf(&b, "\t%s = %q\n", m.constName, m.method)
	}
	b.WriteString(")\n\n")

	b.WriteString("// MethodInfo describes a single LSP request or notification.\n")
	b.WriteString("type MethodInfo struct {\n")
	b.WriteString("\tMethod string\n\tDirection MessageDirection\n\tKind string\n\tParamsType string\n\tResultType string\n}\n\n")
	b.WriteString("// Methods is the registry of every request and notification in the model.\n")
	b.WriteString("var Methods = []MethodInfo{\n")
	for i := range msgs {
		m := &msgs[i]
		fmt.Fprintf(&b, "\t{Method: %s, Direction: %q, Kind: %q, ParamsType: %q, ResultType: %q},\n",
			m.constName, m.direction, m.kind, m.params, m.result)
	}
	b.WriteString("}\n")
	return b.String()
}

func (g *Generator) paramsType(p Params, hint string) string {
	switch len(p) {
	case 0:
		return ""
	case 1:
		return g.lower(p[0], hint)
	default:
		// Multiple positional params: describe as a comma-joined tuple.
		parts := make([]string, len(p))
		for i, t := range p {
			parts[i] = g.lower(t, fmt.Sprintf("%s%d", hint, i))
		}
		return strings.Join(parts, ", ")
	}
}

func (g *Generator) lowerOrNil(t *Type, hint string) string {
	if t == nil {
		return ""
	}
	return g.lower(t, hint)
}

// ---- doc helpers ----

func (g *Generator) docComment(name, doc, since, deprecated string, proposed bool) string {
	return g.fieldDocText(name, doc, since, deprecated, proposed)
}

func (g *Generator) fieldDoc(name string, p *Property) string {
	return g.fieldDocText(name, p.Documentation, p.Since, p.Deprecated, p.Proposed)
}

// fieldDocText builds a godoc comment block beginning with name. Every field
// (documentation, since, deprecated) may contain embedded newlines, so each
// physical line is emitted with its own comment prefix.
func (g *Generator) fieldDocText(name, doc, since, deprecated string, proposed bool) string {
	clean := func(s string) string { return strings.ReplaceAll(s, "\r\n", "\n") }
	var lines []string
	doc = sanitizeDoc(strings.TrimSpace(clean(doc)))
	if doc == "" {
		lines = append(lines, name+" is defined by the LSP specification.")
	} else {
		docLines := strings.Split(doc, "\n")
		docLines[0] = name + " " + docLines[0]
		lines = append(lines, docLines...)
	}
	if proposed {
		lines = append(lines, "", "Proposed.")
	}
	if since != "" {
		lines = append(lines, "", "Since: "+clean(since))
	}
	if deprecated != "" {
		lines = append(lines, "", "Deprecated: "+clean(deprecated))
	}
	var b strings.Builder
	for _, ln := range lines {
		for phys := range strings.SplitSeq(ln, "\n") {
			phys = strings.TrimRight(phys, " \t")
			if phys == "" {
				b.WriteString("//\n")
			} else {
				b.WriteString("// ")
				b.WriteString(phys)
				b.WriteString("\n")
			}
		}
	}
	return b.String()
}

// JSDoc-style annotation patterns the LSP meta-model embeds in documentation
// prose. They are stripped at emit time so the godoc reads as plain Go prose;
// the structured since/deprecated/proposed fields still drive the dedicated
// Since:/Deprecated:/Proposed. lines.
var (
	// linkRe matches a {@link target display text} or {@linkcode ...} reference
	// whose target is converted into a Go doc link.
	linkRe = regexp.MustCompile(`\{@link(?:code)?\s+([^}]*)\}`)
	// sinceRe matches a leading "@since <version>" tag, optionally followed by a
	// "- proposed" status marker or a "- " separator before changelog prose.
	sinceRe = regexp.MustCompile(`(?im)^[ \t]*@since\b[ \t]*(?:version[ \t]+)?[0-9][0-9.]*[ \t]*(?:-[ \t]*proposed\b[ \t]*)?(?:-[ \t]*)?`)
	// inlineSinceRe matches a mid-sentence "@since <version>" tag, e.g. "... is
	// deprecated @since 3.16.0." Unlike sinceRe it stops at the last version
	// digit (\d+(?:\.\d+)*, not [0-9][0-9.]*) so a sentence-terminating period
	// stays attached to the surrounding prose; the two patterns differ on
	// purpose.
	inlineSinceRe = regexp.MustCompile(`[ \t]*@since\b[ \t]*(?:version[ \t]+)?\d+(?:\.\d+)*`)
	// deprRe matches a leading "@deprecated" tag; the prose duplicates the
	// structured Deprecated: directive, so the whole line is dropped.
	deprRe = regexp.MustCompile(`(?im)^[ \t]*@deprecated\b[ \t]*`)
	// blankRunRe collapses paragraph gaps left behind by removed lines.
	blankRunRe = regexp.MustCompile(`\n{3,}`)
)

// unwrapLink converts the body of a {@link} reference into a Go doc link,
// bracketing the target symbol and discarding any trailing display text:
// "Uri.scheme scheme" becomes "[Uri.scheme]". Targets that resolve to an
// exported identifier render as clickable doc links; others render as literal
// bracketed text.
func unwrapLink(body string) string {
	body = strings.TrimSpace(body)
	if body == "" {
		return ""
	}
	target, _, _ := strings.Cut(body, " ")
	return "[" + strings.TrimSpace(target) + "]"
}

// sanitizeDoc removes JSDoc-style @since and @deprecated tags and converts
// {@link}/{@linkcode} references into Go doc links from a documentation block.
// Standalone @since lines are dropped entirely while trailing changelog prose
// is preserved; the duplicated @deprecated prose is dropped in favor of the
// structured directive.
func sanitizeDoc(doc string) string {
	doc = linkRe.ReplaceAllStringFunc(doc, func(m string) string {
		return unwrapLink(linkRe.FindStringSubmatch(m)[1])
	})
	out := make([]string, 0, strings.Count(doc, "\n")+1)
	for ln := range strings.SplitSeq(doc, "\n") {
		if sinceRe.MatchString(ln) {
			if rest := strings.TrimSpace(sinceRe.ReplaceAllString(ln, "")); rest != "" {
				out = append(out, rest)
			}
			continue
		}
		if deprRe.MatchString(ln) {
			continue
		}
		out = append(out, ln)
	}
	res := inlineSinceRe.ReplaceAllString(strings.Join(out, "\n"), "")
	res = blankRunRe.ReplaceAllString(res, "\n\n")
	return strings.TrimSpace(res)
}

// ---- small string helpers ----

func indent(block, prefix string) string {
	lines := strings.Split(strings.TrimRight(block, "\n"), "\n")
	var b strings.Builder
	for _, ln := range lines {
		b.WriteString(prefix)
		b.WriteString(ln)
		b.WriteString("\n")
	}
	return b.String()
}

func quoteByte(t byte) string {
	return "'" + string(rune(t)) + "'"
}

func keySetSignature(keys []string) string {
	s := append([]string(nil), keys...)
	sort.Strings(s)
	return strings.Join(s, ",")
}

func quoteList(keys []string) string {
	parts := make([]string, len(keys))
	for i, k := range keys {
		parts[i] = strconv.Quote(k)
	}
	return strings.Join(parts, ", ")
}

// quoteSlice renders keys as a Go string-slice literal, e.g. []string{"a", "b"}.
func quoteSlice(keys []string) string {
	return "[]string{" + quoteList(keys) + "}"
}

// objectGuard returns the guard expression for an object arm whose required and
// full key sets are required and all. When both are present it emits the fused
// objectHasAndKnown call so the arm scans the object once; otherwise it emits
// the single applicable predicate. It returns "" when neither carries a signal,
// in which case the caller defers the arm to the lenient tier.
func objectGuard(required, all []string) string {
	switch {
	case len(required) > 0 && len(all) > 0:
		return fmt.Sprintf("objectHasAndKnownGuard(raw, %s, %s)", quoteSlice(required), quoteSlice(all))
	case len(required) > 0:
		return fmt.Sprintf("objectHasKeys(raw, %s)", quoteList(required))
	case len(all) > 0:
		return fmt.Sprintf("objectKeysKnown(raw, %s)", quoteList(all))
	default:
		return ""
	}
}

// arrayGuard is objectGuard for an array arm, probing the first element.
func arrayGuard(required, all []string) string {
	switch {
	case len(required) > 0 && len(all) > 0:
		return fmt.Sprintf("arrayFirstHasAndKnown(raw, %s, %s)", quoteSlice(required), quoteSlice(all))
	case len(required) > 0:
		return fmt.Sprintf("arrayFirstHasKeys(raw, %s)", quoteList(required))
	case len(all) > 0:
		return fmt.Sprintf("arrayFirstKeysKnown(raw, %s)", quoteList(all))
	default:
		return ""
	}
}
