name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test/${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-slim
          - ubuntu-24.04-arm

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Check versions
        run: |
          go version
          go env

      - name: Test and take a coverage
        env:
          GOTESTSUM_FORMAT: standard-verbose
        run: |
          mkdir -p _output
          make coverage

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v6
        with:
          report_type: coverage
          flags: ${{ runner.os }}-${{ runner.arch }}
          use_oidc: true
          verbose: true

      - name: Upload test results
        if: always()
        uses: codecov/codecov-action@v6
        with:
          report_type: test_results
          name: test-results
          directory: _test_results/

  lint:
    name: lint
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Run fmt and lint for sources
        run: |-
          make lint
          git add -N . && git diff --exit-code
